#!/usr/bin/env python3
"""Generate the fixed-simulator C++ fixture binding from the immutable JSON."""

from __future__ import annotations

import argparse
from pathlib import Path

from campaign import load_fixture


def render(fixture_path: Path) -> str:
    fixture, digest = load_fixture(fixture_path)
    pods = {pod["identity"]: pod for pod in fixture["pods"]}
    rounds = fixture["rounds"]
    lines = [
        "// Generated by generate_fixed_fixture.py; do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace scoring_fixture {",
        f'inline constexpr std::string_view kFixtureId = "{fixture["fixture_id"]}";',
        f'inline constexpr std::string_view kFixtureSha256 = "{digest}";',
        f"inline constexpr size_t kRoundCount = {len(rounds)};",
        "struct Round {",
        "    uint32_t index;",
        "    uint32_t roundToken;",
        "    uint16_t fixedPodId;",
        "    std::string_view identity;",
        "    bool hit;",
        "    uint32_t reactionTimeUs;",
        "    uint32_t timeoutUs;",
        "};",
        "inline constexpr std::array<Round, kRoundCount> kRounds = {{",
    ]
    for item in rounds:
        pod = pods[item["target_identity"]]
        reaction = item["reaction_time_us"] or 0
        hit = "true" if item["hit"] else "false"
        lines.append(
            f'    {{{item["index"]}, {item["round_token"]}, {pod["fixed_id"]}, '
            f'"{item["target_identity"]}", {hit}, {reaction}, {item["timeout_us"]}}},'
        )
    lines.extend(["}};", "}  // namespace scoring_fixture", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(args.fixture)
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            raise SystemExit(f"generated fixture is stale: {args.output}")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
