/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domes_config_Color, domes_config_Color, AUTO)


PB_BIND(domes_config_FeatureState, domes_config_FeatureState, AUTO)


PB_BIND(domes_config_ListFeaturesRequest, domes_config_ListFeaturesRequest, AUTO)


PB_BIND(domes_config_SetFeatureRequest, domes_config_SetFeatureRequest, AUTO)


PB_BIND(domes_config_LedPattern, domes_config_LedPattern, AUTO)


PB_BIND(domes_config_SetLedPatternRequest, domes_config_SetLedPatternRequest, AUTO)


PB_BIND(domes_config_GetLedPatternRequest, domes_config_GetLedPatternRequest, AUTO)


PB_BIND(domes_config_ListFeaturesResponse, domes_config_ListFeaturesResponse, AUTO)


PB_BIND(domes_config_SetFeatureResponse, domes_config_SetFeatureResponse, AUTO)


PB_BIND(domes_config_SetLedPatternResponse, domes_config_SetLedPatternResponse, AUTO)


PB_BIND(domes_config_GetLedPatternResponse, domes_config_GetLedPatternResponse, AUTO)


PB_BIND(domes_config_SetImuTriageRequest, domes_config_SetImuTriageRequest, AUTO)


PB_BIND(domes_config_SetImuTriageResponse, domes_config_SetImuTriageResponse, AUTO)


PB_BIND(domes_config_GetModeRequest, domes_config_GetModeRequest, AUTO)


PB_BIND(domes_config_GetModeResponse, domes_config_GetModeResponse, AUTO)


PB_BIND(domes_config_SetModeRequest, domes_config_SetModeRequest, AUTO)


PB_BIND(domes_config_SetModeResponse, domes_config_SetModeResponse, AUTO)


PB_BIND(domes_config_GetSystemInfoRequest, domes_config_GetSystemInfoRequest, AUTO)


PB_BIND(domes_config_GetSystemInfoResponse, domes_config_GetSystemInfoResponse, AUTO)


PB_BIND(domes_config_ConfigRequest, domes_config_ConfigRequest, AUTO)


PB_BIND(domes_config_ConfigResponse, domes_config_ConfigResponse, AUTO)













