/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domes_config_FeatureState, domes_config_FeatureState, AUTO)


PB_BIND(domes_config_ListFeaturesRequest, domes_config_ListFeaturesRequest, AUTO)


PB_BIND(domes_config_SetFeatureRequest, domes_config_SetFeatureRequest, AUTO)


PB_BIND(domes_config_ListFeaturesResponse, domes_config_ListFeaturesResponse, AUTO)


PB_BIND(domes_config_SetFeatureResponse, domes_config_SetFeatureResponse, AUTO)


PB_BIND(domes_config_ConfigRequest, domes_config_ConfigRequest, AUTO)


PB_BIND(domes_config_ConfigResponse, domes_config_ConfigResponse, AUTO)


PB_BIND(domes_config_RgbColor, domes_config_RgbColor, AUTO)


PB_BIND(domes_config_SetRgbPatternRequest, domes_config_SetRgbPatternRequest, AUTO)


PB_BIND(domes_config_SetRgbPatternResponse, domes_config_SetRgbPatternResponse, AUTO)


PB_BIND(domes_config_GetRgbPatternRequest, domes_config_GetRgbPatternRequest, AUTO)


PB_BIND(domes_config_GetRgbPatternResponse, domes_config_GetRgbPatternResponse, AUTO)


PB_BIND(domes_config_ListRgbPatternsRequest, domes_config_ListRgbPatternsRequest, AUTO)


PB_BIND(domes_config_RgbPatternInfo, domes_config_RgbPatternInfo, AUTO)


PB_BIND(domes_config_ListRgbPatternsResponse, domes_config_ListRgbPatternsResponse, 2)









