/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domes_config_FeatureState, domes_config_FeatureState, AUTO)


PB_BIND(domes_config_ListFeaturesRequest, domes_config_ListFeaturesRequest, AUTO)


PB_BIND(domes_config_SetFeatureRequest, domes_config_SetFeatureRequest, AUTO)


PB_BIND(domes_config_ListFeaturesResponse, domes_config_ListFeaturesResponse, AUTO)


PB_BIND(domes_config_SetFeatureResponse, domes_config_SetFeatureResponse, AUTO)


PB_BIND(domes_config_ConfigRequest, domes_config_ConfigRequest, AUTO)


PB_BIND(domes_config_ConfigResponse, domes_config_ConfigResponse, AUTO)







