/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOMES_CONFIG_PROTO_CONFIG_PB_H_INCLUDED
#define PB_DOMES_CONFIG_PROTO_CONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Status codes for responses */
typedef enum _domes_config_Status {
    domes_config_Status_STATUS_OK = 0,
    domes_config_Status_STATUS_ERROR = 1,
    domes_config_Status_STATUS_INVALID_FEATURE = 2,
    domes_config_Status_STATUS_BUSY = 3
} domes_config_Status;

/* Runtime-toggleable features */
typedef enum _domes_config_Feature {
    domes_config_Feature_FEATURE_UNKNOWN = 0,
    domes_config_Feature_FEATURE_LED_EFFECTS = 1,
    domes_config_Feature_FEATURE_BLE_ADVERTISING = 2,
    domes_config_Feature_FEATURE_WIFI = 3,
    domes_config_Feature_FEATURE_ESP_NOW = 4,
    domes_config_Feature_FEATURE_TOUCH = 5,
    domes_config_Feature_FEATURE_HAPTIC = 6,
    domes_config_Feature_FEATURE_AUDIO = 7
} domes_config_Feature;

/* Available RGB LED patterns */
typedef enum _domes_config_RgbPattern {
    domes_config_RgbPattern_RGB_PATTERN_OFF = 0, /* Turn off all LEDs */
    domes_config_RgbPattern_RGB_PATTERN_SOLID = 1, /* Solid color (uses primary_color) */
    domes_config_RgbPattern_RGB_PATTERN_RAINBOW_CHASE = 2, /* Rainbow colors rotating around the ring */
    domes_config_RgbPattern_RGB_PATTERN_COMET_TAIL = 3, /* Bright dot with fading trail */
    domes_config_RgbPattern_RGB_PATTERN_SPARKLE_FIRE = 4 /* Random sparkling with warm fire colors */
} domes_config_RgbPattern;

/* Struct definitions */
/* Feature with its current state */
typedef struct _domes_config_FeatureState {
    domes_config_Feature feature;
    bool enabled;
} domes_config_FeatureState;

/* Request messages */
typedef struct _domes_config_ListFeaturesRequest { /* Empty - lists all features */
    char dummy_field;
} domes_config_ListFeaturesRequest;

typedef struct _domes_config_SetFeatureRequest {
    domes_config_Feature feature;
    bool enabled;
} domes_config_SetFeatureRequest;

/* Response messages */
typedef struct _domes_config_ListFeaturesResponse {
    pb_size_t features_count;
    domes_config_FeatureState features[16];
} domes_config_ListFeaturesResponse;

typedef struct _domes_config_SetFeatureResponse {
    bool has_feature;
    domes_config_FeatureState feature;
} domes_config_SetFeatureResponse;

/* Top-level request envelope */
typedef struct _domes_config_ConfigRequest {
    pb_size_t which_request;
    union _domes_config_ConfigRequest_request {
        domes_config_ListFeaturesRequest list_features;
        domes_config_SetFeatureRequest set_feature;
    } request;
} domes_config_ConfigRequest;

/* Top-level response envelope */
typedef struct _domes_config_ConfigResponse {
    domes_config_Status status;
    pb_size_t which_response;
    union _domes_config_ConfigResponse_response {
        domes_config_ListFeaturesResponse list_features;
        domes_config_SetFeatureResponse set_feature;
    } response;
} domes_config_ConfigResponse;

/* RGB color value */
typedef struct _domes_config_RgbColor {
    uint32_t r; /* Red (0-255) */
    uint32_t g; /* Green (0-255) */
    uint32_t b; /* Blue (0-255) */
} domes_config_RgbColor;

/* Request to set RGB pattern */
typedef struct _domes_config_SetRgbPatternRequest {
    domes_config_RgbPattern pattern;
    bool has_primary_color;
    domes_config_RgbColor primary_color; /* Primary color (for solid, comet) */
    uint32_t speed_ms; /* Animation speed in milliseconds */
    uint32_t brightness; /* Brightness (0-255) */
} domes_config_SetRgbPatternRequest;

/* Response to set RGB pattern */
typedef struct _domes_config_SetRgbPatternResponse {
    domes_config_RgbPattern active_pattern;
} domes_config_SetRgbPatternResponse;

/* Request to get current RGB pattern */
typedef struct _domes_config_GetRgbPatternRequest { /* Empty - returns current pattern */
    char dummy_field;
} domes_config_GetRgbPatternRequest;

/* Response with current RGB pattern info */
typedef struct _domes_config_GetRgbPatternResponse {
    domes_config_RgbPattern active_pattern;
    bool has_primary_color;
    domes_config_RgbColor primary_color;
    uint32_t speed_ms;
    uint32_t brightness;
} domes_config_GetRgbPatternResponse;

/* Request to list available patterns */
typedef struct _domes_config_ListRgbPatternsRequest { /* Empty - lists all patterns */
    char dummy_field;
} domes_config_ListRgbPatternsRequest;

/* Pattern info for listing */
typedef struct _domes_config_RgbPatternInfo {
    domes_config_RgbPattern pattern;
    char name[32];
    char description[64];
} domes_config_RgbPatternInfo;

/* Response listing available patterns */
typedef struct _domes_config_ListRgbPatternsResponse {
    pb_size_t patterns_count;
    domes_config_RgbPatternInfo patterns[8];
} domes_config_ListRgbPatternsResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _domes_config_Status_MIN domes_config_Status_STATUS_OK
#define _domes_config_Status_MAX domes_config_Status_STATUS_BUSY
#define _domes_config_Status_ARRAYSIZE ((domes_config_Status)(domes_config_Status_STATUS_BUSY+1))

#define _domes_config_Feature_MIN domes_config_Feature_FEATURE_UNKNOWN
#define _domes_config_Feature_MAX domes_config_Feature_FEATURE_AUDIO
#define _domes_config_Feature_ARRAYSIZE ((domes_config_Feature)(domes_config_Feature_FEATURE_AUDIO+1))

#define _domes_config_RgbPattern_MIN domes_config_RgbPattern_RGB_PATTERN_OFF
#define _domes_config_RgbPattern_MAX domes_config_RgbPattern_RGB_PATTERN_SPARKLE_FIRE
#define _domes_config_RgbPattern_ARRAYSIZE ((domes_config_RgbPattern)(domes_config_RgbPattern_RGB_PATTERN_SPARKLE_FIRE+1))

#define domes_config_FeatureState_feature_ENUMTYPE domes_config_Feature


#define domes_config_SetFeatureRequest_feature_ENUMTYPE domes_config_Feature




#define domes_config_ConfigResponse_status_ENUMTYPE domes_config_Status


#define domes_config_SetRgbPatternRequest_pattern_ENUMTYPE domes_config_RgbPattern

#define domes_config_SetRgbPatternResponse_active_pattern_ENUMTYPE domes_config_RgbPattern


#define domes_config_GetRgbPatternResponse_active_pattern_ENUMTYPE domes_config_RgbPattern


#define domes_config_RgbPatternInfo_pattern_ENUMTYPE domes_config_RgbPattern



/* Initializer values for message structs */
#define domes_config_FeatureState_init_default   {_domes_config_Feature_MIN, 0}
#define domes_config_ListFeaturesRequest_init_default {0}
#define domes_config_SetFeatureRequest_init_default {_domes_config_Feature_MIN, 0}
#define domes_config_ListFeaturesResponse_init_default {0, {domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default}}
#define domes_config_SetFeatureResponse_init_default {false, domes_config_FeatureState_init_default}
#define domes_config_ConfigRequest_init_default  {0, {domes_config_ListFeaturesRequest_init_default}}
#define domes_config_ConfigResponse_init_default {_domes_config_Status_MIN, 0, {domes_config_ListFeaturesResponse_init_default}}
#define domes_config_RgbColor_init_default       {0, 0, 0}
#define domes_config_SetRgbPatternRequest_init_default {_domes_config_RgbPattern_MIN, false, domes_config_RgbColor_init_default, 0, 0}
#define domes_config_SetRgbPatternResponse_init_default {_domes_config_RgbPattern_MIN}
#define domes_config_GetRgbPatternRequest_init_default {0}
#define domes_config_GetRgbPatternResponse_init_default {_domes_config_RgbPattern_MIN, false, domes_config_RgbColor_init_default, 0, 0}
#define domes_config_ListRgbPatternsRequest_init_default {0}
#define domes_config_RgbPatternInfo_init_default {_domes_config_RgbPattern_MIN, "", ""}
#define domes_config_ListRgbPatternsResponse_init_default {0, {domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default, domes_config_RgbPatternInfo_init_default}}
#define domes_config_FeatureState_init_zero      {_domes_config_Feature_MIN, 0}
#define domes_config_ListFeaturesRequest_init_zero {0}
#define domes_config_SetFeatureRequest_init_zero {_domes_config_Feature_MIN, 0}
#define domes_config_ListFeaturesResponse_init_zero {0, {domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero}}
#define domes_config_SetFeatureResponse_init_zero {false, domes_config_FeatureState_init_zero}
#define domes_config_ConfigRequest_init_zero     {0, {domes_config_ListFeaturesRequest_init_zero}}
#define domes_config_ConfigResponse_init_zero    {_domes_config_Status_MIN, 0, {domes_config_ListFeaturesResponse_init_zero}}
#define domes_config_RgbColor_init_zero          {0, 0, 0}
#define domes_config_SetRgbPatternRequest_init_zero {_domes_config_RgbPattern_MIN, false, domes_config_RgbColor_init_zero, 0, 0}
#define domes_config_SetRgbPatternResponse_init_zero {_domes_config_RgbPattern_MIN}
#define domes_config_GetRgbPatternRequest_init_zero {0}
#define domes_config_GetRgbPatternResponse_init_zero {_domes_config_RgbPattern_MIN, false, domes_config_RgbColor_init_zero, 0, 0}
#define domes_config_ListRgbPatternsRequest_init_zero {0}
#define domes_config_RgbPatternInfo_init_zero    {_domes_config_RgbPattern_MIN, "", ""}
#define domes_config_ListRgbPatternsResponse_init_zero {0, {domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero, domes_config_RgbPatternInfo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define domes_config_FeatureState_feature_tag    1
#define domes_config_FeatureState_enabled_tag    2
#define domes_config_SetFeatureRequest_feature_tag 1
#define domes_config_SetFeatureRequest_enabled_tag 2
#define domes_config_ListFeaturesResponse_features_tag 1
#define domes_config_SetFeatureResponse_feature_tag 1
#define domes_config_ConfigRequest_list_features_tag 1
#define domes_config_ConfigRequest_set_feature_tag 2
#define domes_config_ConfigResponse_status_tag   1
#define domes_config_ConfigResponse_list_features_tag 2
#define domes_config_ConfigResponse_set_feature_tag 3
#define domes_config_RgbColor_r_tag              1
#define domes_config_RgbColor_g_tag              2
#define domes_config_RgbColor_b_tag              3
#define domes_config_SetRgbPatternRequest_pattern_tag 1
#define domes_config_SetRgbPatternRequest_primary_color_tag 2
#define domes_config_SetRgbPatternRequest_speed_ms_tag 3
#define domes_config_SetRgbPatternRequest_brightness_tag 4
#define domes_config_SetRgbPatternResponse_active_pattern_tag 1
#define domes_config_GetRgbPatternResponse_active_pattern_tag 1
#define domes_config_GetRgbPatternResponse_primary_color_tag 2
#define domes_config_GetRgbPatternResponse_speed_ms_tag 3
#define domes_config_GetRgbPatternResponse_brightness_tag 4
#define domes_config_RgbPatternInfo_pattern_tag  1
#define domes_config_RgbPatternInfo_name_tag     2
#define domes_config_RgbPatternInfo_description_tag 3
#define domes_config_ListRgbPatternsResponse_patterns_tag 1

/* Struct field encoding specification for nanopb */
#define domes_config_FeatureState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    feature,           1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2)
#define domes_config_FeatureState_CALLBACK NULL
#define domes_config_FeatureState_DEFAULT NULL

#define domes_config_ListFeaturesRequest_FIELDLIST(X, a) \

#define domes_config_ListFeaturesRequest_CALLBACK NULL
#define domes_config_ListFeaturesRequest_DEFAULT NULL

#define domes_config_SetFeatureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    feature,           1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2)
#define domes_config_SetFeatureRequest_CALLBACK NULL
#define domes_config_SetFeatureRequest_DEFAULT NULL

#define domes_config_ListFeaturesResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  features,          1)
#define domes_config_ListFeaturesResponse_CALLBACK NULL
#define domes_config_ListFeaturesResponse_DEFAULT NULL
#define domes_config_ListFeaturesResponse_features_MSGTYPE domes_config_FeatureState

#define domes_config_SetFeatureResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  feature,           1)
#define domes_config_SetFeatureResponse_CALLBACK NULL
#define domes_config_SetFeatureResponse_DEFAULT NULL
#define domes_config_SetFeatureResponse_feature_MSGTYPE domes_config_FeatureState

#define domes_config_ConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,list_features,request.list_features),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_feature,request.set_feature),   2)
#define domes_config_ConfigRequest_CALLBACK NULL
#define domes_config_ConfigRequest_DEFAULT NULL
#define domes_config_ConfigRequest_request_list_features_MSGTYPE domes_config_ListFeaturesRequest
#define domes_config_ConfigRequest_request_set_feature_MSGTYPE domes_config_SetFeatureRequest

#define domes_config_ConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,list_features,response.list_features),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,set_feature,response.set_feature),   3)
#define domes_config_ConfigResponse_CALLBACK NULL
#define domes_config_ConfigResponse_DEFAULT NULL
#define domes_config_ConfigResponse_response_list_features_MSGTYPE domes_config_ListFeaturesResponse
#define domes_config_ConfigResponse_response_set_feature_MSGTYPE domes_config_SetFeatureResponse

#define domes_config_RgbColor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3)
#define domes_config_RgbColor_CALLBACK NULL
#define domes_config_RgbColor_DEFAULT NULL

#define domes_config_SetRgbPatternRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    pattern,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  primary_color,     2) \
X(a, STATIC,   SINGULAR, UINT32,   speed_ms,          3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4)
#define domes_config_SetRgbPatternRequest_CALLBACK NULL
#define domes_config_SetRgbPatternRequest_DEFAULT NULL
#define domes_config_SetRgbPatternRequest_primary_color_MSGTYPE domes_config_RgbColor

#define domes_config_SetRgbPatternResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    active_pattern,    1)
#define domes_config_SetRgbPatternResponse_CALLBACK NULL
#define domes_config_SetRgbPatternResponse_DEFAULT NULL

#define domes_config_GetRgbPatternRequest_FIELDLIST(X, a) \

#define domes_config_GetRgbPatternRequest_CALLBACK NULL
#define domes_config_GetRgbPatternRequest_DEFAULT NULL

#define domes_config_GetRgbPatternResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    active_pattern,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  primary_color,     2) \
X(a, STATIC,   SINGULAR, UINT32,   speed_ms,          3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4)
#define domes_config_GetRgbPatternResponse_CALLBACK NULL
#define domes_config_GetRgbPatternResponse_DEFAULT NULL
#define domes_config_GetRgbPatternResponse_primary_color_MSGTYPE domes_config_RgbColor

#define domes_config_ListRgbPatternsRequest_FIELDLIST(X, a) \

#define domes_config_ListRgbPatternsRequest_CALLBACK NULL
#define domes_config_ListRgbPatternsRequest_DEFAULT NULL

#define domes_config_RgbPatternInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    pattern,           1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, STRING,   description,       3)
#define domes_config_RgbPatternInfo_CALLBACK NULL
#define domes_config_RgbPatternInfo_DEFAULT NULL

#define domes_config_ListRgbPatternsResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  patterns,          1)
#define domes_config_ListRgbPatternsResponse_CALLBACK NULL
#define domes_config_ListRgbPatternsResponse_DEFAULT NULL
#define domes_config_ListRgbPatternsResponse_patterns_MSGTYPE domes_config_RgbPatternInfo

extern const pb_msgdesc_t domes_config_FeatureState_msg;
extern const pb_msgdesc_t domes_config_ListFeaturesRequest_msg;
extern const pb_msgdesc_t domes_config_SetFeatureRequest_msg;
extern const pb_msgdesc_t domes_config_ListFeaturesResponse_msg;
extern const pb_msgdesc_t domes_config_SetFeatureResponse_msg;
extern const pb_msgdesc_t domes_config_ConfigRequest_msg;
extern const pb_msgdesc_t domes_config_ConfigResponse_msg;
extern const pb_msgdesc_t domes_config_RgbColor_msg;
extern const pb_msgdesc_t domes_config_SetRgbPatternRequest_msg;
extern const pb_msgdesc_t domes_config_SetRgbPatternResponse_msg;
extern const pb_msgdesc_t domes_config_GetRgbPatternRequest_msg;
extern const pb_msgdesc_t domes_config_GetRgbPatternResponse_msg;
extern const pb_msgdesc_t domes_config_ListRgbPatternsRequest_msg;
extern const pb_msgdesc_t domes_config_RgbPatternInfo_msg;
extern const pb_msgdesc_t domes_config_ListRgbPatternsResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define domes_config_FeatureState_fields &domes_config_FeatureState_msg
#define domes_config_ListFeaturesRequest_fields &domes_config_ListFeaturesRequest_msg
#define domes_config_SetFeatureRequest_fields &domes_config_SetFeatureRequest_msg
#define domes_config_ListFeaturesResponse_fields &domes_config_ListFeaturesResponse_msg
#define domes_config_SetFeatureResponse_fields &domes_config_SetFeatureResponse_msg
#define domes_config_ConfigRequest_fields &domes_config_ConfigRequest_msg
#define domes_config_ConfigResponse_fields &domes_config_ConfigResponse_msg
#define domes_config_RgbColor_fields &domes_config_RgbColor_msg
#define domes_config_SetRgbPatternRequest_fields &domes_config_SetRgbPatternRequest_msg
#define domes_config_SetRgbPatternResponse_fields &domes_config_SetRgbPatternResponse_msg
#define domes_config_GetRgbPatternRequest_fields &domes_config_GetRgbPatternRequest_msg
#define domes_config_GetRgbPatternResponse_fields &domes_config_GetRgbPatternResponse_msg
#define domes_config_ListRgbPatternsRequest_fields &domes_config_ListRgbPatternsRequest_msg
#define domes_config_RgbPatternInfo_fields &domes_config_RgbPatternInfo_msg
#define domes_config_ListRgbPatternsResponse_fields &domes_config_ListRgbPatternsResponse_msg

/* Maximum encoded size of messages (where known) */
#define DOMES_CONFIG_PROTO_CONFIG_PB_H_MAX_SIZE  domes_config_ListRgbPatternsResponse_size
#define domes_config_ConfigRequest_size          6
#define domes_config_ConfigResponse_size         100
#define domes_config_FeatureState_size           4
#define domes_config_GetRgbPatternRequest_size   0
#define domes_config_GetRgbPatternResponse_size  34
#define domes_config_ListFeaturesRequest_size    0
#define domes_config_ListFeaturesResponse_size   96
#define domes_config_ListRgbPatternsRequest_size 0
#define domes_config_ListRgbPatternsResponse_size 816
#define domes_config_RgbColor_size               18
#define domes_config_RgbPatternInfo_size         100
#define domes_config_SetFeatureRequest_size      4
#define domes_config_SetFeatureResponse_size     6
#define domes_config_SetRgbPatternRequest_size   34
#define domes_config_SetRgbPatternResponse_size  2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
