/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOMES_CONFIG_CONFIG_PB_H_INCLUDED
#define PB_DOMES_CONFIG_CONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Frame-level message types for config protocol
 Used in the frame header [0xAA 0x55][Len][MsgType][Payload][CRC32] */
typedef enum _domes_config_MsgType {
    domes_config_MsgType_MSG_TYPE_UNKNOWN = 0,
    /* Config commands (0x20-0x2F range) */
    domes_config_MsgType_MSG_TYPE_LIST_FEATURES_REQ = 32,
    domes_config_MsgType_MSG_TYPE_LIST_FEATURES_RSP = 33,
    domes_config_MsgType_MSG_TYPE_SET_FEATURE_REQ = 34,
    domes_config_MsgType_MSG_TYPE_SET_FEATURE_RSP = 35,
    domes_config_MsgType_MSG_TYPE_GET_FEATURE_REQ = 36,
    domes_config_MsgType_MSG_TYPE_GET_FEATURE_RSP = 37,
    domes_config_MsgType_MSG_TYPE_SET_LED_PATTERN_REQ = 38,
    domes_config_MsgType_MSG_TYPE_SET_LED_PATTERN_RSP = 39,
    domes_config_MsgType_MSG_TYPE_GET_LED_PATTERN_REQ = 40,
    domes_config_MsgType_MSG_TYPE_GET_LED_PATTERN_RSP = 41,
    domes_config_MsgType_MSG_TYPE_SET_IMU_TRIAGE_REQ = 42,
    domes_config_MsgType_MSG_TYPE_SET_IMU_TRIAGE_RSP = 43,
    /* System mode commands (0x30-0x35 range) */
    domes_config_MsgType_MSG_TYPE_GET_MODE_REQ = 48,
    domes_config_MsgType_MSG_TYPE_GET_MODE_RSP = 49,
    domes_config_MsgType_MSG_TYPE_SET_MODE_REQ = 50,
    domes_config_MsgType_MSG_TYPE_SET_MODE_RSP = 51,
    domes_config_MsgType_MSG_TYPE_GET_SYSTEM_INFO_REQ = 52,
    domes_config_MsgType_MSG_TYPE_GET_SYSTEM_INFO_RSP = 53
} domes_config_MsgType;

/* Status codes for responses */
typedef enum _domes_config_Status {
    domes_config_Status_STATUS_OK = 0,
    domes_config_Status_STATUS_ERROR = 1,
    domes_config_Status_STATUS_INVALID_FEATURE = 2,
    domes_config_Status_STATUS_BUSY = 3,
    domes_config_Status_STATUS_INVALID_PATTERN = 4
} domes_config_Status;

/* LED pattern types */
typedef enum _domes_config_LedPatternType {
    domes_config_LedPatternType_LED_PATTERN_OFF = 0,
    domes_config_LedPatternType_LED_PATTERN_SOLID = 1,
    domes_config_LedPatternType_LED_PATTERN_BREATHING = 2,
    domes_config_LedPatternType_LED_PATTERN_COLOR_CYCLE = 3
} domes_config_LedPatternType;

/* Runtime-toggleable features */
typedef enum _domes_config_Feature {
    domes_config_Feature_FEATURE_UNKNOWN = 0,
    domes_config_Feature_FEATURE_LED_EFFECTS = 1,
    domes_config_Feature_FEATURE_BLE_ADVERTISING = 2,
    domes_config_Feature_FEATURE_WIFI = 3,
    domes_config_Feature_FEATURE_ESP_NOW = 4,
    domes_config_Feature_FEATURE_TOUCH = 5,
    domes_config_Feature_FEATURE_HAPTIC = 6,
    domes_config_Feature_FEATURE_AUDIO = 7
} domes_config_Feature;

/* System operating modes */
typedef enum _domes_config_SystemMode {
    domes_config_SystemMode_SYSTEM_MODE_BOOTING = 0,
    domes_config_SystemMode_SYSTEM_MODE_IDLE = 1,
    domes_config_SystemMode_SYSTEM_MODE_TRIAGE = 2,
    domes_config_SystemMode_SYSTEM_MODE_CONNECTED = 3,
    domes_config_SystemMode_SYSTEM_MODE_GAME = 4,
    domes_config_SystemMode_SYSTEM_MODE_ERROR = 5
} domes_config_SystemMode;

/* Struct definitions */
/* RGBW color (0-255 per channel) */
typedef struct _domes_config_Color {
    uint32_t r;
    uint32_t g;
    uint32_t b;
    uint32_t w; /* White channel (ignored for RGB-only LEDs) */
} domes_config_Color;

/* Feature with its current state */
typedef struct _domes_config_FeatureState {
    domes_config_Feature feature;
    bool enabled;
} domes_config_FeatureState;

/* Request messages */
typedef struct _domes_config_ListFeaturesRequest { /* Empty - lists all features */
    char dummy_field;
} domes_config_ListFeaturesRequest;

typedef struct _domes_config_SetFeatureRequest {
    domes_config_Feature feature;
    bool enabled;
} domes_config_SetFeatureRequest;

/* LED pattern with parameters */
typedef struct _domes_config_LedPattern {
    domes_config_LedPatternType type;
    bool has_color;
    domes_config_Color color; /* Primary color (for solid/breathing) */
    pb_size_t colors_count;
    domes_config_Color colors[8]; /* Color list (for color_cycle) */
    uint32_t period_ms; /* Animation period in ms */
    uint32_t brightness; /* Global brightness (0-255) */
} domes_config_LedPattern;

typedef struct _domes_config_SetLedPatternRequest {
    bool has_pattern;
    domes_config_LedPattern pattern;
} domes_config_SetLedPatternRequest;

typedef struct _domes_config_GetLedPatternRequest { /* Empty - returns current pattern */
    char dummy_field;
} domes_config_GetLedPatternRequest;

/* Response messages */
typedef struct _domes_config_ListFeaturesResponse {
    pb_size_t features_count;
    domes_config_FeatureState features[16];
} domes_config_ListFeaturesResponse;

typedef struct _domes_config_SetFeatureResponse {
    bool has_feature;
    domes_config_FeatureState feature;
} domes_config_SetFeatureResponse;

typedef struct _domes_config_SetLedPatternResponse {
    bool has_pattern;
    domes_config_LedPattern pattern;
} domes_config_SetLedPatternResponse;

typedef struct _domes_config_GetLedPatternResponse {
    bool has_pattern;
    domes_config_LedPattern pattern;
} domes_config_GetLedPatternResponse;

/* IMU triage mode messages */
typedef struct _domes_config_SetImuTriageRequest {
    bool enabled;
} domes_config_SetImuTriageRequest;

typedef struct _domes_config_SetImuTriageResponse {
    bool enabled;
} domes_config_SetImuTriageResponse;

/* System mode messages */
typedef struct _domes_config_GetModeRequest { /* Empty - returns current mode */
    char dummy_field;
} domes_config_GetModeRequest;

typedef struct _domes_config_GetModeResponse {
    domes_config_SystemMode mode;
    uint32_t time_in_mode_ms;
} domes_config_GetModeResponse;

typedef struct _domes_config_SetModeRequest {
    domes_config_SystemMode mode;
} domes_config_SetModeRequest;

typedef struct _domes_config_SetModeResponse {
    domes_config_SystemMode mode;
    bool transition_ok;
} domes_config_SetModeResponse;

typedef struct _domes_config_GetSystemInfoRequest { /* Empty - returns system info */
    char dummy_field;
} domes_config_GetSystemInfoRequest;

typedef struct _domes_config_GetSystemInfoResponse {
    char firmware_version[32];
    uint32_t uptime_s;
    uint32_t free_heap;
    uint32_t boot_count;
    domes_config_SystemMode mode;
    uint32_t feature_mask;
} domes_config_GetSystemInfoResponse;

/* Top-level request envelope */
typedef struct _domes_config_ConfigRequest {
    pb_size_t which_request;
    union _domes_config_ConfigRequest_request {
        domes_config_ListFeaturesRequest list_features;
        domes_config_SetFeatureRequest set_feature;
    } request;
} domes_config_ConfigRequest;

/* Top-level response envelope */
typedef struct _domes_config_ConfigResponse {
    domes_config_Status status;
    pb_size_t which_response;
    union _domes_config_ConfigResponse_response {
        domes_config_ListFeaturesResponse list_features;
        domes_config_SetFeatureResponse set_feature;
    } response;
} domes_config_ConfigResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _domes_config_MsgType_MIN domes_config_MsgType_MSG_TYPE_UNKNOWN
#define _domes_config_MsgType_MAX domes_config_MsgType_MSG_TYPE_GET_SYSTEM_INFO_RSP
#define _domes_config_MsgType_ARRAYSIZE ((domes_config_MsgType)(domes_config_MsgType_MSG_TYPE_GET_SYSTEM_INFO_RSP+1))

#define _domes_config_Status_MIN domes_config_Status_STATUS_OK
#define _domes_config_Status_MAX domes_config_Status_STATUS_INVALID_PATTERN
#define _domes_config_Status_ARRAYSIZE ((domes_config_Status)(domes_config_Status_STATUS_INVALID_PATTERN+1))

#define _domes_config_LedPatternType_MIN domes_config_LedPatternType_LED_PATTERN_OFF
#define _domes_config_LedPatternType_MAX domes_config_LedPatternType_LED_PATTERN_COLOR_CYCLE
#define _domes_config_LedPatternType_ARRAYSIZE ((domes_config_LedPatternType)(domes_config_LedPatternType_LED_PATTERN_COLOR_CYCLE+1))

#define _domes_config_Feature_MIN domes_config_Feature_FEATURE_UNKNOWN
#define _domes_config_Feature_MAX domes_config_Feature_FEATURE_AUDIO
#define _domes_config_Feature_ARRAYSIZE ((domes_config_Feature)(domes_config_Feature_FEATURE_AUDIO+1))

#define _domes_config_SystemMode_MIN domes_config_SystemMode_SYSTEM_MODE_BOOTING
#define _domes_config_SystemMode_MAX domes_config_SystemMode_SYSTEM_MODE_ERROR
#define _domes_config_SystemMode_ARRAYSIZE ((domes_config_SystemMode)(domes_config_SystemMode_SYSTEM_MODE_ERROR+1))


#define domes_config_FeatureState_feature_ENUMTYPE domes_config_Feature


#define domes_config_SetFeatureRequest_feature_ENUMTYPE domes_config_Feature

#define domes_config_LedPattern_type_ENUMTYPE domes_config_LedPatternType










#define domes_config_GetModeResponse_mode_ENUMTYPE domes_config_SystemMode

#define domes_config_SetModeRequest_mode_ENUMTYPE domes_config_SystemMode

#define domes_config_SetModeResponse_mode_ENUMTYPE domes_config_SystemMode


#define domes_config_GetSystemInfoResponse_mode_ENUMTYPE domes_config_SystemMode


#define domes_config_ConfigResponse_status_ENUMTYPE domes_config_Status


/* Initializer values for message structs */
#define domes_config_Color_init_default          {0, 0, 0, 0}
#define domes_config_FeatureState_init_default   {_domes_config_Feature_MIN, 0}
#define domes_config_ListFeaturesRequest_init_default {0}
#define domes_config_SetFeatureRequest_init_default {_domes_config_Feature_MIN, 0}
#define domes_config_LedPattern_init_default     {_domes_config_LedPatternType_MIN, false, domes_config_Color_init_default, 0, {domes_config_Color_init_default, domes_config_Color_init_default, domes_config_Color_init_default, domes_config_Color_init_default, domes_config_Color_init_default, domes_config_Color_init_default, domes_config_Color_init_default, domes_config_Color_init_default}, 0, 0}
#define domes_config_SetLedPatternRequest_init_default {false, domes_config_LedPattern_init_default}
#define domes_config_GetLedPatternRequest_init_default {0}
#define domes_config_ListFeaturesResponse_init_default {0, {domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default, domes_config_FeatureState_init_default}}
#define domes_config_SetFeatureResponse_init_default {false, domes_config_FeatureState_init_default}
#define domes_config_SetLedPatternResponse_init_default {false, domes_config_LedPattern_init_default}
#define domes_config_GetLedPatternResponse_init_default {false, domes_config_LedPattern_init_default}
#define domes_config_SetImuTriageRequest_init_default {0}
#define domes_config_SetImuTriageResponse_init_default {0}
#define domes_config_GetModeRequest_init_default {0}
#define domes_config_GetModeResponse_init_default {_domes_config_SystemMode_MIN, 0}
#define domes_config_SetModeRequest_init_default {_domes_config_SystemMode_MIN}
#define domes_config_SetModeResponse_init_default {_domes_config_SystemMode_MIN, 0}
#define domes_config_GetSystemInfoRequest_init_default {0}
#define domes_config_GetSystemInfoResponse_init_default {"", 0, 0, 0, _domes_config_SystemMode_MIN, 0}
#define domes_config_ConfigRequest_init_default  {0, {domes_config_ListFeaturesRequest_init_default}}
#define domes_config_ConfigResponse_init_default {_domes_config_Status_MIN, 0, {domes_config_ListFeaturesResponse_init_default}}
#define domes_config_Color_init_zero             {0, 0, 0, 0}
#define domes_config_FeatureState_init_zero      {_domes_config_Feature_MIN, 0}
#define domes_config_ListFeaturesRequest_init_zero {0}
#define domes_config_SetFeatureRequest_init_zero {_domes_config_Feature_MIN, 0}
#define domes_config_LedPattern_init_zero        {_domes_config_LedPatternType_MIN, false, domes_config_Color_init_zero, 0, {domes_config_Color_init_zero, domes_config_Color_init_zero, domes_config_Color_init_zero, domes_config_Color_init_zero, domes_config_Color_init_zero, domes_config_Color_init_zero, domes_config_Color_init_zero, domes_config_Color_init_zero}, 0, 0}
#define domes_config_SetLedPatternRequest_init_zero {false, domes_config_LedPattern_init_zero}
#define domes_config_GetLedPatternRequest_init_zero {0}
#define domes_config_ListFeaturesResponse_init_zero {0, {domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero, domes_config_FeatureState_init_zero}}
#define domes_config_SetFeatureResponse_init_zero {false, domes_config_FeatureState_init_zero}
#define domes_config_SetLedPatternResponse_init_zero {false, domes_config_LedPattern_init_zero}
#define domes_config_GetLedPatternResponse_init_zero {false, domes_config_LedPattern_init_zero}
#define domes_config_SetImuTriageRequest_init_zero {0}
#define domes_config_SetImuTriageResponse_init_zero {0}
#define domes_config_GetModeRequest_init_zero    {0}
#define domes_config_GetModeResponse_init_zero   {_domes_config_SystemMode_MIN, 0}
#define domes_config_SetModeRequest_init_zero    {_domes_config_SystemMode_MIN}
#define domes_config_SetModeResponse_init_zero   {_domes_config_SystemMode_MIN, 0}
#define domes_config_GetSystemInfoRequest_init_zero {0}
#define domes_config_GetSystemInfoResponse_init_zero {"", 0, 0, 0, _domes_config_SystemMode_MIN, 0}
#define domes_config_ConfigRequest_init_zero     {0, {domes_config_ListFeaturesRequest_init_zero}}
#define domes_config_ConfigResponse_init_zero    {_domes_config_Status_MIN, 0, {domes_config_ListFeaturesResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define domes_config_Color_r_tag                 1
#define domes_config_Color_g_tag                 2
#define domes_config_Color_b_tag                 3
#define domes_config_Color_w_tag                 4
#define domes_config_FeatureState_feature_tag    1
#define domes_config_FeatureState_enabled_tag    2
#define domes_config_SetFeatureRequest_feature_tag 1
#define domes_config_SetFeatureRequest_enabled_tag 2
#define domes_config_LedPattern_type_tag         1
#define domes_config_LedPattern_color_tag        2
#define domes_config_LedPattern_colors_tag       3
#define domes_config_LedPattern_period_ms_tag    4
#define domes_config_LedPattern_brightness_tag   5
#define domes_config_SetLedPatternRequest_pattern_tag 1
#define domes_config_ListFeaturesResponse_features_tag 1
#define domes_config_SetFeatureResponse_feature_tag 1
#define domes_config_SetLedPatternResponse_pattern_tag 1
#define domes_config_GetLedPatternResponse_pattern_tag 1
#define domes_config_SetImuTriageRequest_enabled_tag 1
#define domes_config_SetImuTriageResponse_enabled_tag 1
#define domes_config_GetModeResponse_mode_tag    1
#define domes_config_GetModeResponse_time_in_mode_ms_tag 2
#define domes_config_SetModeRequest_mode_tag     1
#define domes_config_SetModeResponse_mode_tag    1
#define domes_config_SetModeResponse_transition_ok_tag 2
#define domes_config_GetSystemInfoResponse_firmware_version_tag 1
#define domes_config_GetSystemInfoResponse_uptime_s_tag 2
#define domes_config_GetSystemInfoResponse_free_heap_tag 3
#define domes_config_GetSystemInfoResponse_boot_count_tag 4
#define domes_config_GetSystemInfoResponse_mode_tag 5
#define domes_config_GetSystemInfoResponse_feature_mask_tag 6
#define domes_config_ConfigRequest_list_features_tag 1
#define domes_config_ConfigRequest_set_feature_tag 2
#define domes_config_ConfigResponse_status_tag   1
#define domes_config_ConfigResponse_list_features_tag 2
#define domes_config_ConfigResponse_set_feature_tag 3

/* Struct field encoding specification for nanopb */
#define domes_config_Color_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3) \
X(a, STATIC,   SINGULAR, UINT32,   w,                 4)
#define domes_config_Color_CALLBACK NULL
#define domes_config_Color_DEFAULT NULL

#define domes_config_FeatureState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    feature,           1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2)
#define domes_config_FeatureState_CALLBACK NULL
#define domes_config_FeatureState_DEFAULT NULL

#define domes_config_ListFeaturesRequest_FIELDLIST(X, a) \

#define domes_config_ListFeaturesRequest_CALLBACK NULL
#define domes_config_ListFeaturesRequest_DEFAULT NULL

#define domes_config_SetFeatureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    feature,           1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2)
#define domes_config_SetFeatureRequest_CALLBACK NULL
#define domes_config_SetFeatureRequest_DEFAULT NULL

#define domes_config_LedPattern_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             2) \
X(a, STATIC,   REPEATED, MESSAGE,  colors,            3) \
X(a, STATIC,   SINGULAR, UINT32,   period_ms,         4) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        5)
#define domes_config_LedPattern_CALLBACK NULL
#define domes_config_LedPattern_DEFAULT NULL
#define domes_config_LedPattern_color_MSGTYPE domes_config_Color
#define domes_config_LedPattern_colors_MSGTYPE domes_config_Color

#define domes_config_SetLedPatternRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pattern,           1)
#define domes_config_SetLedPatternRequest_CALLBACK NULL
#define domes_config_SetLedPatternRequest_DEFAULT NULL
#define domes_config_SetLedPatternRequest_pattern_MSGTYPE domes_config_LedPattern

#define domes_config_GetLedPatternRequest_FIELDLIST(X, a) \

#define domes_config_GetLedPatternRequest_CALLBACK NULL
#define domes_config_GetLedPatternRequest_DEFAULT NULL

#define domes_config_ListFeaturesResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  features,          1)
#define domes_config_ListFeaturesResponse_CALLBACK NULL
#define domes_config_ListFeaturesResponse_DEFAULT NULL
#define domes_config_ListFeaturesResponse_features_MSGTYPE domes_config_FeatureState

#define domes_config_SetFeatureResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  feature,           1)
#define domes_config_SetFeatureResponse_CALLBACK NULL
#define domes_config_SetFeatureResponse_DEFAULT NULL
#define domes_config_SetFeatureResponse_feature_MSGTYPE domes_config_FeatureState

#define domes_config_SetLedPatternResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pattern,           1)
#define domes_config_SetLedPatternResponse_CALLBACK NULL
#define domes_config_SetLedPatternResponse_DEFAULT NULL
#define domes_config_SetLedPatternResponse_pattern_MSGTYPE domes_config_LedPattern

#define domes_config_GetLedPatternResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pattern,           1)
#define domes_config_GetLedPatternResponse_CALLBACK NULL
#define domes_config_GetLedPatternResponse_DEFAULT NULL
#define domes_config_GetLedPatternResponse_pattern_MSGTYPE domes_config_LedPattern

#define domes_config_SetImuTriageRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1)
#define domes_config_SetImuTriageRequest_CALLBACK NULL
#define domes_config_SetImuTriageRequest_DEFAULT NULL

#define domes_config_SetImuTriageResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1)
#define domes_config_SetImuTriageResponse_CALLBACK NULL
#define domes_config_SetImuTriageResponse_DEFAULT NULL

#define domes_config_GetModeRequest_FIELDLIST(X, a) \

#define domes_config_GetModeRequest_CALLBACK NULL
#define domes_config_GetModeRequest_DEFAULT NULL

#define domes_config_GetModeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, UINT32,   time_in_mode_ms,   2)
#define domes_config_GetModeResponse_CALLBACK NULL
#define domes_config_GetModeResponse_DEFAULT NULL

#define domes_config_SetModeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define domes_config_SetModeRequest_CALLBACK NULL
#define domes_config_SetModeRequest_DEFAULT NULL

#define domes_config_SetModeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, BOOL,     transition_ok,     2)
#define domes_config_SetModeResponse_CALLBACK NULL
#define domes_config_SetModeResponse_DEFAULT NULL

#define domes_config_GetSystemInfoRequest_FIELDLIST(X, a) \

#define domes_config_GetSystemInfoRequest_CALLBACK NULL
#define domes_config_GetSystemInfoRequest_DEFAULT NULL

#define domes_config_GetSystemInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          2) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap,         3) \
X(a, STATIC,   SINGULAR, UINT32,   boot_count,        4) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              5) \
X(a, STATIC,   SINGULAR, UINT32,   feature_mask,      6)
#define domes_config_GetSystemInfoResponse_CALLBACK NULL
#define domes_config_GetSystemInfoResponse_DEFAULT NULL

#define domes_config_ConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,list_features,request.list_features),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_feature,request.set_feature),   2)
#define domes_config_ConfigRequest_CALLBACK NULL
#define domes_config_ConfigRequest_DEFAULT NULL
#define domes_config_ConfigRequest_request_list_features_MSGTYPE domes_config_ListFeaturesRequest
#define domes_config_ConfigRequest_request_set_feature_MSGTYPE domes_config_SetFeatureRequest

#define domes_config_ConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,list_features,response.list_features),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,set_feature,response.set_feature),   3)
#define domes_config_ConfigResponse_CALLBACK NULL
#define domes_config_ConfigResponse_DEFAULT NULL
#define domes_config_ConfigResponse_response_list_features_MSGTYPE domes_config_ListFeaturesResponse
#define domes_config_ConfigResponse_response_set_feature_MSGTYPE domes_config_SetFeatureResponse

extern const pb_msgdesc_t domes_config_Color_msg;
extern const pb_msgdesc_t domes_config_FeatureState_msg;
extern const pb_msgdesc_t domes_config_ListFeaturesRequest_msg;
extern const pb_msgdesc_t domes_config_SetFeatureRequest_msg;
extern const pb_msgdesc_t domes_config_LedPattern_msg;
extern const pb_msgdesc_t domes_config_SetLedPatternRequest_msg;
extern const pb_msgdesc_t domes_config_GetLedPatternRequest_msg;
extern const pb_msgdesc_t domes_config_ListFeaturesResponse_msg;
extern const pb_msgdesc_t domes_config_SetFeatureResponse_msg;
extern const pb_msgdesc_t domes_config_SetLedPatternResponse_msg;
extern const pb_msgdesc_t domes_config_GetLedPatternResponse_msg;
extern const pb_msgdesc_t domes_config_SetImuTriageRequest_msg;
extern const pb_msgdesc_t domes_config_SetImuTriageResponse_msg;
extern const pb_msgdesc_t domes_config_GetModeRequest_msg;
extern const pb_msgdesc_t domes_config_GetModeResponse_msg;
extern const pb_msgdesc_t domes_config_SetModeRequest_msg;
extern const pb_msgdesc_t domes_config_SetModeResponse_msg;
extern const pb_msgdesc_t domes_config_GetSystemInfoRequest_msg;
extern const pb_msgdesc_t domes_config_GetSystemInfoResponse_msg;
extern const pb_msgdesc_t domes_config_ConfigRequest_msg;
extern const pb_msgdesc_t domes_config_ConfigResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define domes_config_Color_fields &domes_config_Color_msg
#define domes_config_FeatureState_fields &domes_config_FeatureState_msg
#define domes_config_ListFeaturesRequest_fields &domes_config_ListFeaturesRequest_msg
#define domes_config_SetFeatureRequest_fields &domes_config_SetFeatureRequest_msg
#define domes_config_LedPattern_fields &domes_config_LedPattern_msg
#define domes_config_SetLedPatternRequest_fields &domes_config_SetLedPatternRequest_msg
#define domes_config_GetLedPatternRequest_fields &domes_config_GetLedPatternRequest_msg
#define domes_config_ListFeaturesResponse_fields &domes_config_ListFeaturesResponse_msg
#define domes_config_SetFeatureResponse_fields &domes_config_SetFeatureResponse_msg
#define domes_config_SetLedPatternResponse_fields &domes_config_SetLedPatternResponse_msg
#define domes_config_GetLedPatternResponse_fields &domes_config_GetLedPatternResponse_msg
#define domes_config_SetImuTriageRequest_fields &domes_config_SetImuTriageRequest_msg
#define domes_config_SetImuTriageResponse_fields &domes_config_SetImuTriageResponse_msg
#define domes_config_GetModeRequest_fields &domes_config_GetModeRequest_msg
#define domes_config_GetModeResponse_fields &domes_config_GetModeResponse_msg
#define domes_config_SetModeRequest_fields &domes_config_SetModeRequest_msg
#define domes_config_SetModeResponse_fields &domes_config_SetModeResponse_msg
#define domes_config_GetSystemInfoRequest_fields &domes_config_GetSystemInfoRequest_msg
#define domes_config_GetSystemInfoResponse_fields &domes_config_GetSystemInfoResponse_msg
#define domes_config_ConfigRequest_fields &domes_config_ConfigRequest_msg
#define domes_config_ConfigResponse_fields &domes_config_ConfigResponse_msg

/* Maximum encoded size of messages (where known) */
#define DOMES_CONFIG_CONFIG_PB_H_MAX_SIZE        domes_config_SetLedPatternRequest_size
#define domes_config_Color_size                  24
#define domes_config_ConfigRequest_size          6
#define domes_config_ConfigResponse_size         100
#define domes_config_FeatureState_size           4
#define domes_config_GetLedPatternRequest_size   0
#define domes_config_GetLedPatternResponse_size  251
#define domes_config_GetModeRequest_size         0
#define domes_config_GetModeResponse_size        8
#define domes_config_GetSystemInfoRequest_size   0
#define domes_config_GetSystemInfoResponse_size  59
#define domes_config_LedPattern_size             248
#define domes_config_ListFeaturesRequest_size    0
#define domes_config_ListFeaturesResponse_size   96
#define domes_config_SetFeatureRequest_size      4
#define domes_config_SetFeatureResponse_size     6
#define domes_config_SetImuTriageRequest_size    2
#define domes_config_SetImuTriageResponse_size   2
#define domes_config_SetLedPatternRequest_size   251
#define domes_config_SetLedPatternResponse_size  251
#define domes_config_SetModeRequest_size         2
#define domes_config_SetModeResponse_size        4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
