/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOMES_PEER_PEER_DRILL_PB_H_INCLUDED
#define PB_DOMES_PEER_PEER_DRILL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _domes_peer_ContractVersion {
    domes_peer_ContractVersion_CONTRACT_VERSION_UNSPECIFIED = 0,
    domes_peer_ContractVersion_CONTRACT_VERSION_1 = 1
} domes_peer_ContractVersion;

typedef enum _domes_peer_PeerRole {
    domes_peer_PeerRole_PEER_ROLE_UNSPECIFIED = 0,
    domes_peer_PeerRole_PEER_ROLE_MASTER = 1,
    domes_peer_PeerRole_PEER_ROLE_SLAVE = 2
} domes_peer_PeerRole;

typedef enum _domes_peer_PeerLifecycleState {
    domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_UNSPECIFIED = 0,
    domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_DISCOVERY = 1,
    domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_READY = 2,
    domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_ARMED = 3,
    domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_STOPPED = 4
} domes_peer_PeerLifecycleState;

/* Values deliberately match the deployed ESP-NOW type byte. */
typedef enum _domes_peer_PeerMessageType {
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_UNKNOWN = 0,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_BEACON = 1,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_PING = 2,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_PONG = 3,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_JOIN_GAME = 16,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_ARM_TOUCH = 17,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_SET_COLOR = 18,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_STOP_ALL = 19,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_SIMULATE_TOUCH = 20,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_TOUCH_EVENT = 32,
    domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_TIMEOUT_EVENT = 33
} domes_peer_PeerMessageType;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) domes_peer_PeerHeader_sender_mac_t;
typedef struct _domes_peer_PeerHeader {
    domes_peer_ContractVersion version;
    uint32_t src_pod_id;
    uint32_t dst_pod_id; /* 65535 means broadcast. */
    domes_peer_PeerRole sender_role;
    uint64_t timestamp_us;
    uint32_t sequence;
    domes_peer_PeerHeader_sender_mac_t sender_mac; /* Exactly six bytes when carried by ESP-NOW. */
} domes_peer_PeerHeader;

typedef struct _domes_peer_Beacon {
    char dummy_field;
} domes_peer_Beacon;

typedef struct _domes_peer_Ping {
    char dummy_field;
} domes_peer_Ping;

typedef struct _domes_peer_Pong {
    char dummy_field;
} domes_peer_Pong;

typedef struct _domes_peer_JoinGame {
    domes_peer_PeerRole assigned_role;
} domes_peer_JoinGame;

typedef struct _domes_peer_ArmTouch {
    uint32_t round_token;
    uint32_t timeout_ms;
    uint32_t feedback_mode;
} domes_peer_ArmTouch;

typedef struct _domes_peer_SetColor {
    uint32_t r;
    uint32_t g;
    uint32_t b;
} domes_peer_SetColor;

typedef struct _domes_peer_StopAll {
    char dummy_field;
} domes_peer_StopAll;

typedef struct _domes_peer_SimulateTouch {
    uint32_t round_token;
    uint32_t pad_index;
} domes_peer_SimulateTouch;

typedef struct _domes_peer_TouchEvent {
    uint32_t round_token;
    uint32_t reaction_time_us;
    uint32_t pad_index;
} domes_peer_TouchEvent;

typedef struct _domes_peer_TimeoutEvent {
    uint32_t round_token;
} domes_peer_TimeoutEvent;

typedef struct _domes_peer_PeerMessage {
    bool has_header;
    domes_peer_PeerHeader header;
    pb_size_t which_payload;
    union _domes_peer_PeerMessage_payload {
        domes_peer_Beacon beacon;
        domes_peer_Ping ping;
        domes_peer_Pong pong;
        domes_peer_JoinGame join_game;
        domes_peer_ArmTouch arm_touch;
        domes_peer_SetColor set_color;
        domes_peer_StopAll stop_all;
        domes_peer_SimulateTouch simulate_touch;
        domes_peer_TouchEvent touch_event;
        domes_peer_TimeoutEvent timeout_event;
    } payload;
} domes_peer_PeerMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _domes_peer_ContractVersion_MIN domes_peer_ContractVersion_CONTRACT_VERSION_UNSPECIFIED
#define _domes_peer_ContractVersion_MAX domes_peer_ContractVersion_CONTRACT_VERSION_1
#define _domes_peer_ContractVersion_ARRAYSIZE ((domes_peer_ContractVersion)(domes_peer_ContractVersion_CONTRACT_VERSION_1+1))

#define _domes_peer_PeerRole_MIN domes_peer_PeerRole_PEER_ROLE_UNSPECIFIED
#define _domes_peer_PeerRole_MAX domes_peer_PeerRole_PEER_ROLE_SLAVE
#define _domes_peer_PeerRole_ARRAYSIZE ((domes_peer_PeerRole)(domes_peer_PeerRole_PEER_ROLE_SLAVE+1))

#define _domes_peer_PeerLifecycleState_MIN domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_UNSPECIFIED
#define _domes_peer_PeerLifecycleState_MAX domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_STOPPED
#define _domes_peer_PeerLifecycleState_ARRAYSIZE ((domes_peer_PeerLifecycleState)(domes_peer_PeerLifecycleState_PEER_LIFECYCLE_STATE_STOPPED+1))

#define _domes_peer_PeerMessageType_MIN domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_UNKNOWN
#define _domes_peer_PeerMessageType_MAX domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_TIMEOUT_EVENT
#define _domes_peer_PeerMessageType_ARRAYSIZE ((domes_peer_PeerMessageType)(domes_peer_PeerMessageType_PEER_MESSAGE_TYPE_TIMEOUT_EVENT+1))

#define domes_peer_PeerHeader_version_ENUMTYPE domes_peer_ContractVersion
#define domes_peer_PeerHeader_sender_role_ENUMTYPE domes_peer_PeerRole




#define domes_peer_JoinGame_assigned_role_ENUMTYPE domes_peer_PeerRole









/* Initializer values for message structs */
#define domes_peer_PeerHeader_init_default       {_domes_peer_ContractVersion_MIN, 0, 0, _domes_peer_PeerRole_MIN, 0, 0, {0, {0}}}
#define domes_peer_Beacon_init_default           {0}
#define domes_peer_Ping_init_default             {0}
#define domes_peer_Pong_init_default             {0}
#define domes_peer_JoinGame_init_default         {_domes_peer_PeerRole_MIN}
#define domes_peer_ArmTouch_init_default         {0, 0, 0}
#define domes_peer_SetColor_init_default         {0, 0, 0}
#define domes_peer_StopAll_init_default          {0}
#define domes_peer_SimulateTouch_init_default    {0, 0}
#define domes_peer_TouchEvent_init_default       {0, 0, 0}
#define domes_peer_TimeoutEvent_init_default     {0}
#define domes_peer_PeerMessage_init_default      {false, domes_peer_PeerHeader_init_default, 0, {domes_peer_Beacon_init_default}}
#define domes_peer_PeerHeader_init_zero          {_domes_peer_ContractVersion_MIN, 0, 0, _domes_peer_PeerRole_MIN, 0, 0, {0, {0}}}
#define domes_peer_Beacon_init_zero              {0}
#define domes_peer_Ping_init_zero                {0}
#define domes_peer_Pong_init_zero                {0}
#define domes_peer_JoinGame_init_zero            {_domes_peer_PeerRole_MIN}
#define domes_peer_ArmTouch_init_zero            {0, 0, 0}
#define domes_peer_SetColor_init_zero            {0, 0, 0}
#define domes_peer_StopAll_init_zero             {0}
#define domes_peer_SimulateTouch_init_zero       {0, 0}
#define domes_peer_TouchEvent_init_zero          {0, 0, 0}
#define domes_peer_TimeoutEvent_init_zero        {0}
#define domes_peer_PeerMessage_init_zero         {false, domes_peer_PeerHeader_init_zero, 0, {domes_peer_Beacon_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define domes_peer_PeerHeader_version_tag        1
#define domes_peer_PeerHeader_src_pod_id_tag     2
#define domes_peer_PeerHeader_dst_pod_id_tag     3
#define domes_peer_PeerHeader_sender_role_tag    4
#define domes_peer_PeerHeader_timestamp_us_tag   5
#define domes_peer_PeerHeader_sequence_tag       6
#define domes_peer_PeerHeader_sender_mac_tag     7
#define domes_peer_JoinGame_assigned_role_tag    1
#define domes_peer_ArmTouch_round_token_tag      1
#define domes_peer_ArmTouch_timeout_ms_tag       2
#define domes_peer_ArmTouch_feedback_mode_tag    3
#define domes_peer_SetColor_r_tag                1
#define domes_peer_SetColor_g_tag                2
#define domes_peer_SetColor_b_tag                3
#define domes_peer_SimulateTouch_round_token_tag 1
#define domes_peer_SimulateTouch_pad_index_tag   2
#define domes_peer_TouchEvent_round_token_tag    1
#define domes_peer_TouchEvent_reaction_time_us_tag 2
#define domes_peer_TouchEvent_pad_index_tag      3
#define domes_peer_TimeoutEvent_round_token_tag  1
#define domes_peer_PeerMessage_header_tag        1
#define domes_peer_PeerMessage_beacon_tag        16
#define domes_peer_PeerMessage_ping_tag          17
#define domes_peer_PeerMessage_pong_tag          18
#define domes_peer_PeerMessage_join_game_tag     19
#define domes_peer_PeerMessage_arm_touch_tag     20
#define domes_peer_PeerMessage_set_color_tag     21
#define domes_peer_PeerMessage_stop_all_tag      22
#define domes_peer_PeerMessage_simulate_touch_tag 23
#define domes_peer_PeerMessage_touch_event_tag   24
#define domes_peer_PeerMessage_timeout_event_tag 25

/* Struct field encoding specification for nanopb */
#define domes_peer_PeerHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   src_pod_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   dst_pod_id,        3) \
X(a, STATIC,   SINGULAR, UENUM,    sender_role,       4) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      5) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          6) \
X(a, STATIC,   SINGULAR, BYTES,    sender_mac,        7)
#define domes_peer_PeerHeader_CALLBACK NULL
#define domes_peer_PeerHeader_DEFAULT NULL

#define domes_peer_Beacon_FIELDLIST(X, a) \

#define domes_peer_Beacon_CALLBACK NULL
#define domes_peer_Beacon_DEFAULT NULL

#define domes_peer_Ping_FIELDLIST(X, a) \

#define domes_peer_Ping_CALLBACK NULL
#define domes_peer_Ping_DEFAULT NULL

#define domes_peer_Pong_FIELDLIST(X, a) \

#define domes_peer_Pong_CALLBACK NULL
#define domes_peer_Pong_DEFAULT NULL

#define domes_peer_JoinGame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    assigned_role,     1)
#define domes_peer_JoinGame_CALLBACK NULL
#define domes_peer_JoinGame_DEFAULT NULL

#define domes_peer_ArmTouch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   round_token,       1) \
X(a, STATIC,   SINGULAR, UINT32,   timeout_ms,        2) \
X(a, STATIC,   SINGULAR, UINT32,   feedback_mode,     3)
#define domes_peer_ArmTouch_CALLBACK NULL
#define domes_peer_ArmTouch_DEFAULT NULL

#define domes_peer_SetColor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3)
#define domes_peer_SetColor_CALLBACK NULL
#define domes_peer_SetColor_DEFAULT NULL

#define domes_peer_StopAll_FIELDLIST(X, a) \

#define domes_peer_StopAll_CALLBACK NULL
#define domes_peer_StopAll_DEFAULT NULL

#define domes_peer_SimulateTouch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   round_token,       1) \
X(a, STATIC,   SINGULAR, UINT32,   pad_index,         2)
#define domes_peer_SimulateTouch_CALLBACK NULL
#define domes_peer_SimulateTouch_DEFAULT NULL

#define domes_peer_TouchEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   round_token,       1) \
X(a, STATIC,   SINGULAR, UINT32,   reaction_time_us,   2) \
X(a, STATIC,   SINGULAR, UINT32,   pad_index,         3)
#define domes_peer_TouchEvent_CALLBACK NULL
#define domes_peer_TouchEvent_DEFAULT NULL

#define domes_peer_TimeoutEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   round_token,       1)
#define domes_peer_TimeoutEvent_CALLBACK NULL
#define domes_peer_TimeoutEvent_DEFAULT NULL

#define domes_peer_PeerMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,beacon,payload.beacon),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping,payload.ping),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pong,payload.pong),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,join_game,payload.join_game),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,arm_touch,payload.arm_touch),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_color,payload.set_color),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop_all,payload.stop_all),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,simulate_touch,payload.simulate_touch),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,touch_event,payload.touch_event),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,timeout_event,payload.timeout_event),  25)
#define domes_peer_PeerMessage_CALLBACK NULL
#define domes_peer_PeerMessage_DEFAULT NULL
#define domes_peer_PeerMessage_header_MSGTYPE domes_peer_PeerHeader
#define domes_peer_PeerMessage_payload_beacon_MSGTYPE domes_peer_Beacon
#define domes_peer_PeerMessage_payload_ping_MSGTYPE domes_peer_Ping
#define domes_peer_PeerMessage_payload_pong_MSGTYPE domes_peer_Pong
#define domes_peer_PeerMessage_payload_join_game_MSGTYPE domes_peer_JoinGame
#define domes_peer_PeerMessage_payload_arm_touch_MSGTYPE domes_peer_ArmTouch
#define domes_peer_PeerMessage_payload_set_color_MSGTYPE domes_peer_SetColor
#define domes_peer_PeerMessage_payload_stop_all_MSGTYPE domes_peer_StopAll
#define domes_peer_PeerMessage_payload_simulate_touch_MSGTYPE domes_peer_SimulateTouch
#define domes_peer_PeerMessage_payload_touch_event_MSGTYPE domes_peer_TouchEvent
#define domes_peer_PeerMessage_payload_timeout_event_MSGTYPE domes_peer_TimeoutEvent

extern const pb_msgdesc_t domes_peer_PeerHeader_msg;
extern const pb_msgdesc_t domes_peer_Beacon_msg;
extern const pb_msgdesc_t domes_peer_Ping_msg;
extern const pb_msgdesc_t domes_peer_Pong_msg;
extern const pb_msgdesc_t domes_peer_JoinGame_msg;
extern const pb_msgdesc_t domes_peer_ArmTouch_msg;
extern const pb_msgdesc_t domes_peer_SetColor_msg;
extern const pb_msgdesc_t domes_peer_StopAll_msg;
extern const pb_msgdesc_t domes_peer_SimulateTouch_msg;
extern const pb_msgdesc_t domes_peer_TouchEvent_msg;
extern const pb_msgdesc_t domes_peer_TimeoutEvent_msg;
extern const pb_msgdesc_t domes_peer_PeerMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define domes_peer_PeerHeader_fields &domes_peer_PeerHeader_msg
#define domes_peer_Beacon_fields &domes_peer_Beacon_msg
#define domes_peer_Ping_fields &domes_peer_Ping_msg
#define domes_peer_Pong_fields &domes_peer_Pong_msg
#define domes_peer_JoinGame_fields &domes_peer_JoinGame_msg
#define domes_peer_ArmTouch_fields &domes_peer_ArmTouch_msg
#define domes_peer_SetColor_fields &domes_peer_SetColor_msg
#define domes_peer_StopAll_fields &domes_peer_StopAll_msg
#define domes_peer_SimulateTouch_fields &domes_peer_SimulateTouch_msg
#define domes_peer_TouchEvent_fields &domes_peer_TouchEvent_msg
#define domes_peer_TimeoutEvent_fields &domes_peer_TimeoutEvent_msg
#define domes_peer_PeerMessage_fields &domes_peer_PeerMessage_msg

/* Maximum encoded size of messages (where known) */
#define DOMES_PEER_PEER_DRILL_PB_H_MAX_SIZE      domes_peer_PeerMessage_size
#define domes_peer_ArmTouch_size                 18
#define domes_peer_Beacon_size                   0
#define domes_peer_JoinGame_size                 2
#define domes_peer_PeerHeader_size               41
#define domes_peer_PeerMessage_size              64
#define domes_peer_Ping_size                     0
#define domes_peer_Pong_size                     0
#define domes_peer_SetColor_size                 18
#define domes_peer_SimulateTouch_size            12
#define domes_peer_StopAll_size                  0
#define domes_peer_TimeoutEvent_size             6
#define domes_peer_TouchEvent_size               18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
