/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "peer_drill.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domes_peer_PeerHeader, domes_peer_PeerHeader, AUTO)


PB_BIND(domes_peer_Beacon, domes_peer_Beacon, AUTO)


PB_BIND(domes_peer_Ping, domes_peer_Ping, AUTO)


PB_BIND(domes_peer_Pong, domes_peer_Pong, AUTO)


PB_BIND(domes_peer_JoinGame, domes_peer_JoinGame, AUTO)


PB_BIND(domes_peer_ArmTouch, domes_peer_ArmTouch, AUTO)


PB_BIND(domes_peer_SetColor, domes_peer_SetColor, AUTO)


PB_BIND(domes_peer_StopAll, domes_peer_StopAll, AUTO)


PB_BIND(domes_peer_SimulateTouch, domes_peer_SimulateTouch, AUTO)


PB_BIND(domes_peer_TouchEvent, domes_peer_TouchEvent, AUTO)


PB_BIND(domes_peer_TimeoutEvent, domes_peer_TimeoutEvent, AUTO)


PB_BIND(domes_peer_PeerMessage, domes_peer_PeerMessage, AUTO)
