/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOMES_PEER_DRILL_PEER_DRILL_PB_H_INCLUDED
#define PB_DOMES_PEER_DRILL_PEER_DRILL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Existing feedback bitmask values. Values outside this enum are invalid. */
typedef enum _domes_peer_drill_FeedbackMode {
    domes_peer_drill_FeedbackMode_FEEDBACK_MODE_NONE = 0,
    domes_peer_drill_FeedbackMode_FEEDBACK_MODE_LED = 1,
    domes_peer_drill_FeedbackMode_FEEDBACK_MODE_AUDIO = 2,
    domes_peer_drill_FeedbackMode_FEEDBACK_MODE_LED_AND_AUDIO = 3
} domes_peer_drill_FeedbackMode;

/* Struct definitions */
typedef struct _domes_peer_drill_Beacon {
    char dummy_field;
} domes_peer_drill_Beacon;

typedef struct _domes_peer_drill_Ping {
    char dummy_field;
} domes_peer_drill_Ping;

typedef struct _domes_peer_drill_Pong {
    char dummy_field;
} domes_peer_drill_Pong;

typedef struct _domes_peer_drill_JoinGame {
    char dummy_field;
} domes_peer_drill_JoinGame;

typedef struct _domes_peer_drill_StopAll {
    char dummy_field;
} domes_peer_drill_StopAll;

typedef struct _domes_peer_drill_ArmTouch {
    uint32_t round_token;
    uint32_t timeout_ms;
    domes_peer_drill_FeedbackMode feedback_mode;
} domes_peer_drill_ArmTouch;

typedef struct _domes_peer_drill_SetColor {
    uint32_t red;
    uint32_t green;
    uint32_t blue;
} domes_peer_drill_SetColor;

typedef struct _domes_peer_drill_SimulateTouch {
    uint32_t round_token;
    uint32_t pad_index;
} domes_peer_drill_SimulateTouch;

typedef struct _domes_peer_drill_TouchEvent {
    uint32_t round_token;
    uint32_t reaction_time_us;
    uint32_t pad_index;
} domes_peer_drill_TouchEvent;

typedef struct _domes_peer_drill_TimeoutEvent {
    uint32_t round_token;
} domes_peer_drill_TimeoutEvent;

typedef PB_BYTES_ARRAY_T(6) domes_peer_drill_PeerMessage_sender_mac_t;
typedef struct _domes_peer_drill_PeerMessage {
    /* The compatibility codec accepts exactly 1 without adding a byte to the
 unchanged Legacy-V1 ESP-NOW packet. */
    uint32_t protocol_version;
    domes_peer_drill_PeerMessage_sender_mac_t sender_mac;
    uint32_t sender_timestamp_us;
    pb_size_t which_payload;
    union _domes_peer_drill_PeerMessage_payload {
        domes_peer_drill_Beacon beacon;
        domes_peer_drill_Ping ping;
        domes_peer_drill_Pong pong;
        domes_peer_drill_JoinGame join_game;
        domes_peer_drill_ArmTouch arm_touch;
        domes_peer_drill_SetColor set_color;
        domes_peer_drill_StopAll stop_all;
        domes_peer_drill_SimulateTouch simulate_touch;
        domes_peer_drill_TouchEvent touch_event;
        domes_peer_drill_TimeoutEvent timeout_event;
    } payload;
} domes_peer_drill_PeerMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _domes_peer_drill_FeedbackMode_MIN domes_peer_drill_FeedbackMode_FEEDBACK_MODE_NONE
#define _domes_peer_drill_FeedbackMode_MAX domes_peer_drill_FeedbackMode_FEEDBACK_MODE_LED_AND_AUDIO
#define _domes_peer_drill_FeedbackMode_ARRAYSIZE ((domes_peer_drill_FeedbackMode)(domes_peer_drill_FeedbackMode_FEEDBACK_MODE_LED_AND_AUDIO+1))






#define domes_peer_drill_ArmTouch_feedback_mode_ENUMTYPE domes_peer_drill_FeedbackMode







/* Initializer values for message structs */
#define domes_peer_drill_Beacon_init_default     {0}
#define domes_peer_drill_Ping_init_default       {0}
#define domes_peer_drill_Pong_init_default       {0}
#define domes_peer_drill_JoinGame_init_default   {0}
#define domes_peer_drill_StopAll_init_default    {0}
#define domes_peer_drill_ArmTouch_init_default   {0, 0, _domes_peer_drill_FeedbackMode_MIN}
#define domes_peer_drill_SetColor_init_default   {0, 0, 0}
#define domes_peer_drill_SimulateTouch_init_default {0, 0}
#define domes_peer_drill_TouchEvent_init_default {0, 0, 0}
#define domes_peer_drill_TimeoutEvent_init_default {0}
#define domes_peer_drill_PeerMessage_init_default {0, {0, {0}}, 0, 0, {domes_peer_drill_Beacon_init_default}}
#define domes_peer_drill_Beacon_init_zero        {0}
#define domes_peer_drill_Ping_init_zero          {0}
#define domes_peer_drill_Pong_init_zero          {0}
#define domes_peer_drill_JoinGame_init_zero      {0}
#define domes_peer_drill_StopAll_init_zero       {0}
#define domes_peer_drill_ArmTouch_init_zero      {0, 0, _domes_peer_drill_FeedbackMode_MIN}
#define domes_peer_drill_SetColor_init_zero      {0, 0, 0}
#define domes_peer_drill_SimulateTouch_init_zero {0, 0}
#define domes_peer_drill_TouchEvent_init_zero    {0, 0, 0}
#define domes_peer_drill_TimeoutEvent_init_zero  {0}
#define domes_peer_drill_PeerMessage_init_zero   {0, {0, {0}}, 0, 0, {domes_peer_drill_Beacon_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define domes_peer_drill_ArmTouch_round_token_tag 1
#define domes_peer_drill_ArmTouch_timeout_ms_tag 2
#define domes_peer_drill_ArmTouch_feedback_mode_tag 3
#define domes_peer_drill_SetColor_red_tag        1
#define domes_peer_drill_SetColor_green_tag      2
#define domes_peer_drill_SetColor_blue_tag       3
#define domes_peer_drill_SimulateTouch_round_token_tag 1
#define domes_peer_drill_SimulateTouch_pad_index_tag 2
#define domes_peer_drill_TouchEvent_round_token_tag 1
#define domes_peer_drill_TouchEvent_reaction_time_us_tag 2
#define domes_peer_drill_TouchEvent_pad_index_tag 3
#define domes_peer_drill_TimeoutEvent_round_token_tag 1
#define domes_peer_drill_PeerMessage_protocol_version_tag 1
#define domes_peer_drill_PeerMessage_sender_mac_tag 2
#define domes_peer_drill_PeerMessage_sender_timestamp_us_tag 3
#define domes_peer_drill_PeerMessage_beacon_tag  10
#define domes_peer_drill_PeerMessage_ping_tag    11
#define domes_peer_drill_PeerMessage_pong_tag    12
#define domes_peer_drill_PeerMessage_join_game_tag 13
#define domes_peer_drill_PeerMessage_arm_touch_tag 14
#define domes_peer_drill_PeerMessage_set_color_tag 15
#define domes_peer_drill_PeerMessage_stop_all_tag 16
#define domes_peer_drill_PeerMessage_simulate_touch_tag 17
#define domes_peer_drill_PeerMessage_touch_event_tag 18
#define domes_peer_drill_PeerMessage_timeout_event_tag 19

/* Struct field encoding specification for nanopb */
#define domes_peer_drill_Beacon_FIELDLIST(X, a) \

#define domes_peer_drill_Beacon_CALLBACK NULL
#define domes_peer_drill_Beacon_DEFAULT NULL

#define domes_peer_drill_Ping_FIELDLIST(X, a) \

#define domes_peer_drill_Ping_CALLBACK NULL
#define domes_peer_drill_Ping_DEFAULT NULL

#define domes_peer_drill_Pong_FIELDLIST(X, a) \

#define domes_peer_drill_Pong_CALLBACK NULL
#define domes_peer_drill_Pong_DEFAULT NULL

#define domes_peer_drill_JoinGame_FIELDLIST(X, a) \

#define domes_peer_drill_JoinGame_CALLBACK NULL
#define domes_peer_drill_JoinGame_DEFAULT NULL

#define domes_peer_drill_StopAll_FIELDLIST(X, a) \

#define domes_peer_drill_StopAll_CALLBACK NULL
#define domes_peer_drill_StopAll_DEFAULT NULL

#define domes_peer_drill_ArmTouch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  round_token,       1) \
X(a, STATIC,   SINGULAR, UINT32,   timeout_ms,        2) \
X(a, STATIC,   SINGULAR, UENUM,    feedback_mode,     3)
#define domes_peer_drill_ArmTouch_CALLBACK NULL
#define domes_peer_drill_ArmTouch_DEFAULT NULL

#define domes_peer_drill_SetColor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   red,               1) \
X(a, STATIC,   SINGULAR, UINT32,   green,             2) \
X(a, STATIC,   SINGULAR, UINT32,   blue,              3)
#define domes_peer_drill_SetColor_CALLBACK NULL
#define domes_peer_drill_SetColor_DEFAULT NULL

#define domes_peer_drill_SimulateTouch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  round_token,       1) \
X(a, STATIC,   SINGULAR, UINT32,   pad_index,         2)
#define domes_peer_drill_SimulateTouch_CALLBACK NULL
#define domes_peer_drill_SimulateTouch_DEFAULT NULL

#define domes_peer_drill_TouchEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  round_token,       1) \
X(a, STATIC,   SINGULAR, UINT32,   reaction_time_us,   2) \
X(a, STATIC,   SINGULAR, UINT32,   pad_index,         3)
#define domes_peer_drill_TouchEvent_CALLBACK NULL
#define domes_peer_drill_TouchEvent_DEFAULT NULL

#define domes_peer_drill_TimeoutEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  round_token,       1)
#define domes_peer_drill_TimeoutEvent_CALLBACK NULL
#define domes_peer_drill_TimeoutEvent_DEFAULT NULL

#define domes_peer_drill_PeerMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, BYTES,    sender_mac,        2) \
X(a, STATIC,   SINGULAR, FIXED32,  sender_timestamp_us,   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,beacon,payload.beacon),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping,payload.ping),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pong,payload.pong),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,join_game,payload.join_game),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,arm_touch,payload.arm_touch),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_color,payload.set_color),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop_all,payload.stop_all),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,simulate_touch,payload.simulate_touch),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,touch_event,payload.touch_event),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,timeout_event,payload.timeout_event),  19)
#define domes_peer_drill_PeerMessage_CALLBACK NULL
#define domes_peer_drill_PeerMessage_DEFAULT NULL
#define domes_peer_drill_PeerMessage_payload_beacon_MSGTYPE domes_peer_drill_Beacon
#define domes_peer_drill_PeerMessage_payload_ping_MSGTYPE domes_peer_drill_Ping
#define domes_peer_drill_PeerMessage_payload_pong_MSGTYPE domes_peer_drill_Pong
#define domes_peer_drill_PeerMessage_payload_join_game_MSGTYPE domes_peer_drill_JoinGame
#define domes_peer_drill_PeerMessage_payload_arm_touch_MSGTYPE domes_peer_drill_ArmTouch
#define domes_peer_drill_PeerMessage_payload_set_color_MSGTYPE domes_peer_drill_SetColor
#define domes_peer_drill_PeerMessage_payload_stop_all_MSGTYPE domes_peer_drill_StopAll
#define domes_peer_drill_PeerMessage_payload_simulate_touch_MSGTYPE domes_peer_drill_SimulateTouch
#define domes_peer_drill_PeerMessage_payload_touch_event_MSGTYPE domes_peer_drill_TouchEvent
#define domes_peer_drill_PeerMessage_payload_timeout_event_MSGTYPE domes_peer_drill_TimeoutEvent

extern const pb_msgdesc_t domes_peer_drill_Beacon_msg;
extern const pb_msgdesc_t domes_peer_drill_Ping_msg;
extern const pb_msgdesc_t domes_peer_drill_Pong_msg;
extern const pb_msgdesc_t domes_peer_drill_JoinGame_msg;
extern const pb_msgdesc_t domes_peer_drill_StopAll_msg;
extern const pb_msgdesc_t domes_peer_drill_ArmTouch_msg;
extern const pb_msgdesc_t domes_peer_drill_SetColor_msg;
extern const pb_msgdesc_t domes_peer_drill_SimulateTouch_msg;
extern const pb_msgdesc_t domes_peer_drill_TouchEvent_msg;
extern const pb_msgdesc_t domes_peer_drill_TimeoutEvent_msg;
extern const pb_msgdesc_t domes_peer_drill_PeerMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define domes_peer_drill_Beacon_fields &domes_peer_drill_Beacon_msg
#define domes_peer_drill_Ping_fields &domes_peer_drill_Ping_msg
#define domes_peer_drill_Pong_fields &domes_peer_drill_Pong_msg
#define domes_peer_drill_JoinGame_fields &domes_peer_drill_JoinGame_msg
#define domes_peer_drill_StopAll_fields &domes_peer_drill_StopAll_msg
#define domes_peer_drill_ArmTouch_fields &domes_peer_drill_ArmTouch_msg
#define domes_peer_drill_SetColor_fields &domes_peer_drill_SetColor_msg
#define domes_peer_drill_SimulateTouch_fields &domes_peer_drill_SimulateTouch_msg
#define domes_peer_drill_TouchEvent_fields &domes_peer_drill_TouchEvent_msg
#define domes_peer_drill_TimeoutEvent_fields &domes_peer_drill_TimeoutEvent_msg
#define domes_peer_drill_PeerMessage_fields &domes_peer_drill_PeerMessage_msg

/* Maximum encoded size of messages (where known) */
#define DOMES_PEER_DRILL_PEER_DRILL_PB_H_MAX_SIZE domes_peer_drill_PeerMessage_size
#define domes_peer_drill_ArmTouch_size           13
#define domes_peer_drill_Beacon_size             0
#define domes_peer_drill_JoinGame_size           0
#define domes_peer_drill_PeerMessage_size        39
#define domes_peer_drill_Ping_size               0
#define domes_peer_drill_Pong_size               0
#define domes_peer_drill_SetColor_size           18
#define domes_peer_drill_SimulateTouch_size      11
#define domes_peer_drill_StopAll_size            0
#define domes_peer_drill_TimeoutEvent_size       5
#define domes_peer_drill_TouchEvent_size         17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
