/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "peer_drill.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domes_peer_drill_Beacon, domes_peer_drill_Beacon, AUTO)


PB_BIND(domes_peer_drill_Ping, domes_peer_drill_Ping, AUTO)


PB_BIND(domes_peer_drill_Pong, domes_peer_drill_Pong, AUTO)


PB_BIND(domes_peer_drill_JoinGame, domes_peer_drill_JoinGame, AUTO)


PB_BIND(domes_peer_drill_StopAll, domes_peer_drill_StopAll, AUTO)


PB_BIND(domes_peer_drill_ArmTouch, domes_peer_drill_ArmTouch, AUTO)


PB_BIND(domes_peer_drill_SetColor, domes_peer_drill_SetColor, AUTO)


PB_BIND(domes_peer_drill_SimulateTouch, domes_peer_drill_SimulateTouch, AUTO)


PB_BIND(domes_peer_drill_TouchEvent, domes_peer_drill_TouchEvent, AUTO)


PB_BIND(domes_peer_drill_TimeoutEvent, domes_peer_drill_TimeoutEvent, AUTO)


PB_BIND(domes_peer_drill_PeerMessage, domes_peer_drill_PeerMessage, AUTO)
