/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOMES_TRACE_TRACE_PB_H_INCLUDED
#define PB_DOMES_TRACE_TRACE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Frame-level message types for trace protocol (0x10-0x1F range)
 Used in the frame header [0xAA 0x55][Len][MsgType][Payload][CRC32] */
typedef enum _domes_trace_MsgType {
    domes_trace_MsgType_MSG_TYPE_UNKNOWN = 0,
    domes_trace_MsgType_MSG_TYPE_START = 16, /* Start trace recording (host -> device) */
    domes_trace_MsgType_MSG_TYPE_STOP = 17, /* Stop trace recording (host -> device) */
    domes_trace_MsgType_MSG_TYPE_DUMP = 18, /* Request trace dump (host -> device) */
    domes_trace_MsgType_MSG_TYPE_DATA = 19, /* Trace data chunk (device -> host) */
    domes_trace_MsgType_MSG_TYPE_END = 20, /* End of trace dump (device -> host) */
    domes_trace_MsgType_MSG_TYPE_CLEAR = 21, /* Clear trace buffer (host -> device) */
    domes_trace_MsgType_MSG_TYPE_STATUS = 22, /* Query trace status (host -> device) */
    domes_trace_MsgType_MSG_TYPE_ACK = 23 /* Acknowledge command (device -> host) */
} domes_trace_MsgType;

/* Status codes for trace ACK responses */
typedef enum _domes_trace_Status {
    domes_trace_Status_STATUS_OK = 0,
    domes_trace_Status_STATUS_NOT_INIT = 1, /* Trace not initialized */
    domes_trace_Status_STATUS_ALREADY_ON = 2, /* Tracing already enabled */
    domes_trace_Status_STATUS_ALREADY_OFF = 3, /* Tracing already disabled */
    domes_trace_Status_STATUS_BUFFER_EMPTY = 4, /* No events to dump */
    domes_trace_Status_STATUS_ERROR = 255 /* Generic error */
} domes_trace_Status;

/* Categories for trace events (used to filter and color-code in visualization) */
typedef enum _domes_trace_Category {
    domes_trace_Category_CATEGORY_KERNEL = 0, /* FreeRTOS kernel events (task switch, ISR) */
    domes_trace_Category_CATEGORY_TRANSPORT = 1, /* USB/BLE transport operations */
    domes_trace_Category_CATEGORY_OTA = 2, /* OTA update operations */
    domes_trace_Category_CATEGORY_WIFI = 3, /* WiFi/ESP-NOW operations */
    domes_trace_Category_CATEGORY_LED = 4, /* LED animations */
    domes_trace_Category_CATEGORY_AUDIO = 5, /* Audio playback */
    domes_trace_Category_CATEGORY_TOUCH = 6, /* Touch sensing */
    domes_trace_Category_CATEGORY_GAME = 7, /* Game logic */
    domes_trace_Category_CATEGORY_USER = 8, /* User-defined events */
    domes_trace_Category_CATEGORY_HAPTIC = 9, /* Haptic feedback */
    domes_trace_Category_CATEGORY_BLE = 10, /* BLE operations */
    domes_trace_Category_CATEGORY_NVS = 11 /* NVS storage operations */
} domes_trace_Category;

/* Types of trace events */
typedef enum _domes_trace_EventType {
    /* FreeRTOS kernel events (0x01-0x0F) */
    domes_trace_EventType_EVENT_TYPE_UNKNOWN = 0,
    domes_trace_EventType_EVENT_TYPE_TASK_SWITCH_IN = 1, /* Task switched in (began running) */
    domes_trace_EventType_EVENT_TYPE_TASK_SWITCH_OUT = 2, /* Task switched out (stopped running) */
    domes_trace_EventType_EVENT_TYPE_TASK_CREATE = 3, /* Task created */
    domes_trace_EventType_EVENT_TYPE_TASK_DELETE = 4, /* Task deleted */
    domes_trace_EventType_EVENT_TYPE_ISR_ENTER = 5, /* ISR entered */
    domes_trace_EventType_EVENT_TYPE_ISR_EXIT = 6, /* ISR exited */
    domes_trace_EventType_EVENT_TYPE_QUEUE_SEND = 7, /* Queue send operation */
    domes_trace_EventType_EVENT_TYPE_QUEUE_RECEIVE = 8, /* Queue receive operation */
    domes_trace_EventType_EVENT_TYPE_MUTEX_LOCK = 9, /* Mutex acquired */
    domes_trace_EventType_EVENT_TYPE_MUTEX_UNLOCK = 10, /* Mutex released */
    /* Application events (0x20-0x2F) */
    domes_trace_EventType_EVENT_TYPE_SPAN_BEGIN = 32, /* Begin of a duration span */
    domes_trace_EventType_EVENT_TYPE_SPAN_END = 33, /* End of a duration span */
    domes_trace_EventType_EVENT_TYPE_INSTANT = 34, /* Instant/point event */
    domes_trace_EventType_EVENT_TYPE_COUNTER = 35, /* Counter value update */
    domes_trace_EventType_EVENT_TYPE_COMPLETE = 36 /* Complete event (has duration in arg2) */
} domes_trace_EventType;

/* Struct definitions */
/* Compact trace event (16 bytes when serialized as binary)
 Note: For wire efficiency, trace events use fixed binary format, not protobuf.
 This message is for reference/documentation and host-side processing. */
typedef struct _domes_trace_Event {
    uint32_t timestamp; /* Microseconds since boot */
    uint32_t task_id; /* FreeRTOS task number */
    domes_trace_EventType event_type;
    domes_trace_Category category;
    uint32_t arg1; /* Primary argument (span ID, counter ID, ISR number) */
    uint32_t arg2; /* Secondary argument (counter value, duration) */
} domes_trace_Event;

/* Task entry mapping task ID to name */
typedef struct _domes_trace_TaskEntry {
    uint32_t task_id;
    char name[16];
} domes_trace_TaskEntry;

/* Trace metadata sent at start of dump */
typedef struct _domes_trace_Metadata {
    uint32_t event_count; /* Total events in this dump */
    uint32_t dropped_count; /* Events dropped due to buffer full */
    uint32_t start_timestamp; /* First event timestamp (microseconds) */
    uint32_t end_timestamp; /* Last event timestamp (microseconds) */
    pb_size_t tasks_count;
    domes_trace_TaskEntry tasks[32];
} domes_trace_Metadata;

/* Header for trace data chunks */
typedef struct _domes_trace_DataHeader {
    uint32_t offset; /* Event offset in dump (0-based) */
    uint32_t count; /* Number of events in this chunk */
} domes_trace_DataHeader;

/* End of dump message */
typedef struct _domes_trace_DumpEnd {
    uint32_t total_events; /* Total events sent */
    uint32_t checksum; /* Simple checksum of all event data */
} domes_trace_DumpEnd;

/* Status response message */
typedef struct _domes_trace_StatusResponse {
    bool initialized; /* True if trace system initialized */
    bool enabled; /* True if tracing is currently enabled */
    uint32_t event_count; /* Approximate events in buffer */
    uint32_t dropped_count; /* Events dropped since last clear */
    uint32_t buffer_size; /* Total buffer size in bytes */
} domes_trace_StatusResponse;

/* ACK response message */
typedef struct _domes_trace_AckResponse {
    domes_trace_Status status;
} domes_trace_AckResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _domes_trace_MsgType_MIN domes_trace_MsgType_MSG_TYPE_UNKNOWN
#define _domes_trace_MsgType_MAX domes_trace_MsgType_MSG_TYPE_ACK
#define _domes_trace_MsgType_ARRAYSIZE ((domes_trace_MsgType)(domes_trace_MsgType_MSG_TYPE_ACK+1))

#define _domes_trace_Status_MIN domes_trace_Status_STATUS_OK
#define _domes_trace_Status_MAX domes_trace_Status_STATUS_ERROR
#define _domes_trace_Status_ARRAYSIZE ((domes_trace_Status)(domes_trace_Status_STATUS_ERROR+1))

#define _domes_trace_Category_MIN domes_trace_Category_CATEGORY_KERNEL
#define _domes_trace_Category_MAX domes_trace_Category_CATEGORY_NVS
#define _domes_trace_Category_ARRAYSIZE ((domes_trace_Category)(domes_trace_Category_CATEGORY_NVS+1))

#define _domes_trace_EventType_MIN domes_trace_EventType_EVENT_TYPE_UNKNOWN
#define _domes_trace_EventType_MAX domes_trace_EventType_EVENT_TYPE_COMPLETE
#define _domes_trace_EventType_ARRAYSIZE ((domes_trace_EventType)(domes_trace_EventType_EVENT_TYPE_COMPLETE+1))

#define domes_trace_Event_event_type_ENUMTYPE domes_trace_EventType
#define domes_trace_Event_category_ENUMTYPE domes_trace_Category






#define domes_trace_AckResponse_status_ENUMTYPE domes_trace_Status


/* Initializer values for message structs */
#define domes_trace_Event_init_default           {0, 0, _domes_trace_EventType_MIN, _domes_trace_Category_MIN, 0, 0}
#define domes_trace_TaskEntry_init_default       {0, ""}
#define domes_trace_Metadata_init_default        {0, 0, 0, 0, 0, {domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default}}
#define domes_trace_DataHeader_init_default      {0, 0}
#define domes_trace_DumpEnd_init_default         {0, 0}
#define domes_trace_StatusResponse_init_default  {0, 0, 0, 0, 0}
#define domes_trace_AckResponse_init_default     {_domes_trace_Status_MIN}
#define domes_trace_Event_init_zero              {0, 0, _domes_trace_EventType_MIN, _domes_trace_Category_MIN, 0, 0}
#define domes_trace_TaskEntry_init_zero          {0, ""}
#define domes_trace_Metadata_init_zero           {0, 0, 0, 0, 0, {domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero}}
#define domes_trace_DataHeader_init_zero         {0, 0}
#define domes_trace_DumpEnd_init_zero            {0, 0}
#define domes_trace_StatusResponse_init_zero     {0, 0, 0, 0, 0}
#define domes_trace_AckResponse_init_zero        {_domes_trace_Status_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define domes_trace_Event_timestamp_tag          1
#define domes_trace_Event_task_id_tag            2
#define domes_trace_Event_event_type_tag         3
#define domes_trace_Event_category_tag           4
#define domes_trace_Event_arg1_tag               5
#define domes_trace_Event_arg2_tag               6
#define domes_trace_TaskEntry_task_id_tag        1
#define domes_trace_TaskEntry_name_tag           2
#define domes_trace_Metadata_event_count_tag     1
#define domes_trace_Metadata_dropped_count_tag   2
#define domes_trace_Metadata_start_timestamp_tag 3
#define domes_trace_Metadata_end_timestamp_tag   4
#define domes_trace_Metadata_tasks_tag           5
#define domes_trace_DataHeader_offset_tag        1
#define domes_trace_DataHeader_count_tag         2
#define domes_trace_DumpEnd_total_events_tag     1
#define domes_trace_DumpEnd_checksum_tag         2
#define domes_trace_StatusResponse_initialized_tag 1
#define domes_trace_StatusResponse_enabled_tag   2
#define domes_trace_StatusResponse_event_count_tag 3
#define domes_trace_StatusResponse_dropped_count_tag 4
#define domes_trace_StatusResponse_buffer_size_tag 5
#define domes_trace_AckResponse_status_tag       1

/* Struct field encoding specification for nanopb */
#define domes_trace_Event_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   task_id,           2) \
X(a, STATIC,   SINGULAR, UENUM,    event_type,        3) \
X(a, STATIC,   SINGULAR, UENUM,    category,          4) \
X(a, STATIC,   SINGULAR, UINT32,   arg1,              5) \
X(a, STATIC,   SINGULAR, UINT32,   arg2,              6)
#define domes_trace_Event_CALLBACK NULL
#define domes_trace_Event_DEFAULT NULL

#define domes_trace_TaskEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   task_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2)
#define domes_trace_TaskEntry_CALLBACK NULL
#define domes_trace_TaskEntry_DEFAULT NULL

#define domes_trace_Metadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   event_count,       1) \
X(a, STATIC,   SINGULAR, UINT32,   dropped_count,     2) \
X(a, STATIC,   SINGULAR, UINT32,   start_timestamp,   3) \
X(a, STATIC,   SINGULAR, UINT32,   end_timestamp,     4) \
X(a, STATIC,   REPEATED, MESSAGE,  tasks,             5)
#define domes_trace_Metadata_CALLBACK NULL
#define domes_trace_Metadata_DEFAULT NULL
#define domes_trace_Metadata_tasks_MSGTYPE domes_trace_TaskEntry

#define domes_trace_DataHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   count,             2)
#define domes_trace_DataHeader_CALLBACK NULL
#define domes_trace_DataHeader_DEFAULT NULL

#define domes_trace_DumpEnd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_events,      1) \
X(a, STATIC,   SINGULAR, UINT32,   checksum,          2)
#define domes_trace_DumpEnd_CALLBACK NULL
#define domes_trace_DumpEnd_DEFAULT NULL

#define domes_trace_StatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     initialized,       1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2) \
X(a, STATIC,   SINGULAR, UINT32,   event_count,       3) \
X(a, STATIC,   SINGULAR, UINT32,   dropped_count,     4) \
X(a, STATIC,   SINGULAR, UINT32,   buffer_size,       5)
#define domes_trace_StatusResponse_CALLBACK NULL
#define domes_trace_StatusResponse_DEFAULT NULL

#define domes_trace_AckResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define domes_trace_AckResponse_CALLBACK NULL
#define domes_trace_AckResponse_DEFAULT NULL

extern const pb_msgdesc_t domes_trace_Event_msg;
extern const pb_msgdesc_t domes_trace_TaskEntry_msg;
extern const pb_msgdesc_t domes_trace_Metadata_msg;
extern const pb_msgdesc_t domes_trace_DataHeader_msg;
extern const pb_msgdesc_t domes_trace_DumpEnd_msg;
extern const pb_msgdesc_t domes_trace_StatusResponse_msg;
extern const pb_msgdesc_t domes_trace_AckResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define domes_trace_Event_fields &domes_trace_Event_msg
#define domes_trace_TaskEntry_fields &domes_trace_TaskEntry_msg
#define domes_trace_Metadata_fields &domes_trace_Metadata_msg
#define domes_trace_DataHeader_fields &domes_trace_DataHeader_msg
#define domes_trace_DumpEnd_fields &domes_trace_DumpEnd_msg
#define domes_trace_StatusResponse_fields &domes_trace_StatusResponse_msg
#define domes_trace_AckResponse_fields &domes_trace_AckResponse_msg

/* Maximum encoded size of messages (where known) */
#define DOMES_TRACE_TRACE_PB_H_MAX_SIZE          domes_trace_Metadata_size
#define domes_trace_AckResponse_size             3
#define domes_trace_DataHeader_size              12
#define domes_trace_DumpEnd_size                 12
#define domes_trace_Event_size                   28
#define domes_trace_Metadata_size                824
#define domes_trace_StatusResponse_size          22
#define domes_trace_TaskEntry_size               23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
