/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DOMES_TRACE_TRACE_PB_H_INCLUDED
#define PB_DOMES_TRACE_TRACE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Frame-level message types for trace protocol (0x10-0x1B assigned range; 0x18 reserved)
 Used in the frame header [0xAA 0x55][Len][MsgType][Payload][CRC32] */
typedef enum _domes_trace_MsgType {
    domes_trace_MsgType_MSG_TYPE_UNKNOWN = 0,
    domes_trace_MsgType_MSG_TYPE_START = 16, /* Start trace recording (host -> device, empty payload) */
    domes_trace_MsgType_MSG_TYPE_STOP = 17, /* Stop trace recording (host -> device, empty payload) */
    domes_trace_MsgType_MSG_TYPE_DUMP = 18, /* Request trace dump (host -> device, empty payload) */
    domes_trace_MsgType_MSG_TYPE_DATA = 19, /* Trace data chunk (device -> host, TraceDataChunk) */
    domes_trace_MsgType_MSG_TYPE_END = 20, /* End of trace dump (device -> host, TraceDumpComplete) */
    domes_trace_MsgType_MSG_TYPE_CLEAR = 21, /* Clear trace buffer (host -> device, empty payload) */
    domes_trace_MsgType_MSG_TYPE_STATUS_REQ = 22, /* Query trace status (host -> device, empty payload) */
    domes_trace_MsgType_MSG_TYPE_STATUS_RESP = 23, /* Trace status response (device -> host, TraceStatusResponse) */
    domes_trace_MsgType_MSG_TYPE_STREAM_DATA = 25, /* Streamed event batch (device -> host, StreamBatch) */
    domes_trace_MsgType_MSG_TYPE_SESSION_INFO = 26, /* Session metadata (device -> host, TraceSessionInfo) */
    domes_trace_MsgType_MSG_TYPE_ACK = 27 /* Acknowledge command (device -> host, AckResponse) */
} domes_trace_MsgType;

/* Status codes for trace ACK responses */
typedef enum _domes_trace_Status {
    domes_trace_Status_STATUS_OK = 0,
    domes_trace_Status_STATUS_NOT_INIT = 1, /* Trace not initialized */
    domes_trace_Status_STATUS_ALREADY_ON = 2, /* Tracing already enabled */
    domes_trace_Status_STATUS_ALREADY_OFF = 3, /* Tracing already disabled */
    domes_trace_Status_STATUS_BUFFER_EMPTY = 4, /* No events to dump */
    domes_trace_Status_STATUS_ERROR = 255 /* Generic error */
} domes_trace_Status;

/* Categories for trace events (used to filter and color-code in visualization) */
typedef enum _domes_trace_Category {
    domes_trace_Category_CATEGORY_KERNEL = 0, /* Scheduler, ISR, callback, and causal lifecycle events */
    domes_trace_Category_CATEGORY_TRANSPORT = 1, /* UART/TCP/BLE transport operations */
    domes_trace_Category_CATEGORY_OTA = 2, /* OTA update operations */
    domes_trace_Category_CATEGORY_WIFI = 3, /* WiFi/ESP-NOW operations */
    domes_trace_Category_CATEGORY_LED = 4, /* LED animations */
    domes_trace_Category_CATEGORY_AUDIO = 5, /* Audio playback */
    domes_trace_Category_CATEGORY_TOUCH = 6, /* Touch sensing */
    domes_trace_Category_CATEGORY_GAME = 7, /* Game logic */
    domes_trace_Category_CATEGORY_USER = 8, /* User-defined events */
    domes_trace_Category_CATEGORY_HAPTIC = 9, /* Haptic feedback */
    domes_trace_Category_CATEGORY_BLE = 10, /* BLE operations */
    domes_trace_Category_CATEGORY_NVS = 11, /* NVS storage operations */
    domes_trace_Category_CATEGORY_ESPNOW = 12, /* ESP-NOW peer-to-peer operations */
    domes_trace_Category_CATEGORY_SYNC = 13 /* Mutex/semaphore synchronization */
} domes_trace_Category;

/* Types of trace events */
typedef enum _domes_trace_EventType {
    domes_trace_EventType_EVENT_TYPE_UNKNOWN = 0,
    domes_trace_EventType_EVENT_TYPE_MUTEX_LOCK = 9, /* Mutex acquired */
    domes_trace_EventType_EVENT_TYPE_MUTEX_UNLOCK = 10, /* Mutex released */
    /* Synchronization events (0x0B-0x0F) */
    domes_trace_EventType_EVENT_TYPE_MUTEX_CONTENTION = 11, /* Mutex contention: arg1=mutexId, arg2=waitTimeUs */
    domes_trace_EventType_EVENT_TYPE_SEM_TAKE = 12, /* Semaphore take: arg1=semId, arg2=causalId or zero */
    domes_trace_EventType_EVENT_TYPE_SEM_GIVE = 13, /* Semaphore give: arg1=semId, arg2=causalId or zero */
    /* Scheduler and causal observability (format version 1).
 0x18 is intentionally unused to avoid confusion with the reserved frame MsgType. */
    domes_trace_EventType_EVENT_TYPE_SCHED_TASK_CREATE = 16, /* task_id=stable task ID */
    domes_trace_EventType_EVENT_TYPE_SCHED_TASK_DELETE = 17, /* task_id=stable task ID */
    domes_trace_EventType_EVENT_TYPE_SCHED_TASK_READY = 18, /* arg1=cause ID or zero if unavailable, arg2=causal ID or zero */
    domes_trace_EventType_EVENT_TYPE_SCHED_TASK_BLOCK = 19, /* arg1=stable object ID, arg2=timeout ticks */
    domes_trace_EventType_EVENT_TYPE_SCHED_SWITCH_IN = 20, /* task_id/core identify selected task */
    domes_trace_EventType_EVENT_TYPE_SCHED_SWITCH_OUT = 21, /* task_id/core identify descheduled task */
    domes_trace_EventType_EVENT_TYPE_SCHED_ISR_ENTER = 22, /* arg1=stable interrupt ID, arg2=causal ID */
    domes_trace_EventType_EVENT_TYPE_SCHED_ISR_EXIT = 23, /* arg1=stable interrupt ID, arg2=causal ID */
    domes_trace_EventType_EVENT_TYPE_SCHED_QUEUE_SEND = 25, /* arg1=stable queue ID, arg2=causal ID or zero */
    domes_trace_EventType_EVENT_TYPE_SCHED_QUEUE_RECEIVE = 26, /* arg1=stable queue ID, arg2=causal ID or zero */
    domes_trace_EventType_EVENT_TYPE_SCHED_TIMEOUT = 27, /* arg1=stable object ID, arg2=causal ID */
    domes_trace_EventType_EVENT_TYPE_CALLBACK_BEGIN = 28, /* arg1=stable callback ID, arg2=causal ID */
    domes_trace_EventType_EVENT_TYPE_CALLBACK_END = 29, /* arg1=stable callback ID, arg2=causal ID */
    domes_trace_EventType_EVENT_TYPE_CAUSAL_COMPLETE = 30, /* arg1=stable action ID, arg2=causal ID */
    /* Application events (0x20-0x2F) */
    domes_trace_EventType_EVENT_TYPE_SPAN_BEGIN = 32, /* Begin of a duration span */
    domes_trace_EventType_EVENT_TYPE_SPAN_END = 33, /* End of a duration span */
    domes_trace_EventType_EVENT_TYPE_INSTANT = 34, /* Instant/point event */
    domes_trace_EventType_EVENT_TYPE_COUNTER = 35, /* Counter value update */
    domes_trace_EventType_EVENT_TYPE_COMPLETE = 36, /* Complete event (has duration in arg2) */
    domes_trace_EventType_EVENT_TYPE_TRACE_OVERHEAD = 37 /* arg1=disabled and arg2=enabled 32-record time (us) */
} domes_trace_EventType;

typedef enum _domes_trace_ObjectKind {
    domes_trace_ObjectKind_OBJECT_KIND_UNKNOWN = 0,
    domes_trace_ObjectKind_OBJECT_KIND_QUEUE = 1,
    domes_trace_ObjectKind_OBJECT_KIND_SEMAPHORE = 2,
    domes_trace_ObjectKind_OBJECT_KIND_INTERRUPT = 3,
    domes_trace_ObjectKind_OBJECT_KIND_CALLBACK = 4,
    domes_trace_ObjectKind_OBJECT_KIND_ACTION = 5,
    domes_trace_ObjectKind_OBJECT_KIND_MUTEX = 6,
    domes_trace_ObjectKind_OBJECT_KIND_TIMEOUT = 7
} domes_trace_ObjectKind;

/* Struct definitions */
/* Compact trace event (16 bytes when serialized as binary)
 Note: For wire efficiency, trace events use fixed binary format, not protobuf.
 This message is for reference/documentation and host-side processing. */
typedef struct _domes_trace_Event {
    uint32_t timestamp; /* Microseconds since boot */
    uint32_t task_id; /* Immutable task ID assigned during runtime assembly */
    domes_trace_EventType event_type;
    domes_trace_Category category;
    uint32_t arg1; /* Primary argument (span, counter, or synchronization ID) */
    uint32_t arg2; /* Secondary argument (counter value, duration) */
} domes_trace_Event;

/* Task name mapping (task ID -> human-readable name) */
typedef struct _domes_trace_TaskEntry {
    uint32_t task_id;
    char name[16]; /* Max 15 UTF-8 bytes */
    uint32_t priority;
    uint32_t core_affinity_mask; /* bit 0=Core 0, bit 1=Core 1 */
} domes_trace_TaskEntry;

typedef struct _domes_trace_ObjectEntry {
    uint32_t object_id;
    domes_trace_ObjectKind kind;
    char name[16]; /* Max 15 UTF-8 bytes */
} domes_trace_ObjectEntry;

typedef PB_BYTES_ARRAY_T(32) domes_trace_TraceSessionInfo_app_elf_sha256_t;
typedef PB_BYTES_ARRAY_T(32) domes_trace_TraceSessionInfo_app_image_sha256_t;
typedef PB_BYTES_ARRAY_T(6) domes_trace_TraceSessionInfo_device_uid_t;
/* Session metadata sent at start of dump (MsgType: SESSION_INFO 0x1A)
 Replaces the old binary TraceMetadata struct. */
typedef struct _domes_trace_TraceSessionInfo {
    uint32_t pod_id; /* Pod identity (from NVS, 0 if unset) */
    uint32_t event_count; /* Events in this dump */
    uint32_t dropped_count; /* Events dropped (buffer full) */
    uint32_t start_timestamp_us; /* First event timestamp */
    uint32_t end_timestamp_us; /* Last event timestamp */
    pb_size_t tasks_count;
    domes_trace_TaskEntry tasks[16]; /* Registered task names */
    uint32_t buffer_size_bytes; /* Active capture capacity in bytes */
    uint32_t trace_event_format_version; /* 1 for scheduler/causality flags and IDs */
    pb_size_t objects_count;
    domes_trace_ObjectEntry objects[10];
    uint32_t discontinuity_count;
    char firmware_version[32]; /* Running esp_app_desc_t version */
    domes_trace_TraceSessionInfo_app_elf_sha256_t app_elf_sha256; /* Running esp_app_desc_t ELF SHA-256 (32 bytes) */
    domes_trace_TraceSessionInfo_app_image_sha256_t app_image_sha256; /* Verified running app image SHA-256 (32 bytes) */
    domes_trace_TraceSessionInfo_device_uid_t device_uid; /* Factory base MAC, not a transport-derived MAC (6 bytes) */
} domes_trace_TraceSessionInfo;

typedef PB_BYTES_ARRAY_T(256) domes_trace_TraceDataChunk_events_t;
/* Chunk of binary trace events (MsgType: DATA 0x13)
 The events field contains raw 16-byte TraceEvent structs. */
typedef struct _domes_trace_TraceDataChunk {
    uint32_t offset; /* Event offset in dump (0-based) */
    uint32_t count; /* Number of 16-byte events in data */
    domes_trace_TraceDataChunk_events_t events; /* Raw binary: count * 16 bytes of TraceEvent[] */
} domes_trace_TraceDataChunk;

/* End-of-dump marker (MsgType: END 0x14) */
typedef struct _domes_trace_TraceDumpComplete {
    uint32_t total_events;
    uint32_t checksum; /* Simple byte-sum checksum of all event data */
} domes_trace_TraceDumpComplete;

/* Trace status response (MsgType: STATUS_RESP 0x17) */
typedef struct _domes_trace_TraceStatusResponse {
    bool initialized;
    bool enabled; /* Recording to ring buffer */
    bool streaming; /* Real-time streaming active */
    uint32_t event_count; /* Events in buffer */
    uint32_t dropped_count; /* Total drops since last clear */
    uint32_t buffer_size; /* Buffer capacity in bytes */
    uint32_t stream_category_mask; /* Active stream filter (0 = all) */
    uint32_t discontinuity_count; /* Unresolved IDs or unbalanced hook state */
} domes_trace_TraceStatusResponse;

/* ACK response (MsgType: ACK 0x1B) */
typedef struct _domes_trace_AckResponse {
    domes_trace_Status status;
} domes_trace_AckResponse;

typedef PB_BYTES_ARRAY_T(256) domes_trace_StreamBatch_events_t;
/* Streamed event batch (MsgType: STREAM_DATA 0x19, device -> host) */
typedef struct _domes_trace_StreamBatch {
    uint32_t sequence; /* Monotonic sequence number (detect gaps) */
    uint32_t dropped; /* Events dropped since last batch (overflow) */
    domes_trace_StreamBatch_events_t events; /* Raw binary: N * 16 bytes of TraceEvent[] */
} domes_trace_StreamBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _domes_trace_MsgType_MIN domes_trace_MsgType_MSG_TYPE_UNKNOWN
#define _domes_trace_MsgType_MAX domes_trace_MsgType_MSG_TYPE_ACK
#define _domes_trace_MsgType_ARRAYSIZE ((domes_trace_MsgType)(domes_trace_MsgType_MSG_TYPE_ACK+1))

#define _domes_trace_Status_MIN domes_trace_Status_STATUS_OK
#define _domes_trace_Status_MAX domes_trace_Status_STATUS_ERROR
#define _domes_trace_Status_ARRAYSIZE ((domes_trace_Status)(domes_trace_Status_STATUS_ERROR+1))

#define _domes_trace_Category_MIN domes_trace_Category_CATEGORY_KERNEL
#define _domes_trace_Category_MAX domes_trace_Category_CATEGORY_SYNC
#define _domes_trace_Category_ARRAYSIZE ((domes_trace_Category)(domes_trace_Category_CATEGORY_SYNC+1))

#define _domes_trace_EventType_MIN domes_trace_EventType_EVENT_TYPE_UNKNOWN
#define _domes_trace_EventType_MAX domes_trace_EventType_EVENT_TYPE_TRACE_OVERHEAD
#define _domes_trace_EventType_ARRAYSIZE ((domes_trace_EventType)(domes_trace_EventType_EVENT_TYPE_TRACE_OVERHEAD+1))

#define _domes_trace_ObjectKind_MIN domes_trace_ObjectKind_OBJECT_KIND_UNKNOWN
#define _domes_trace_ObjectKind_MAX domes_trace_ObjectKind_OBJECT_KIND_TIMEOUT
#define _domes_trace_ObjectKind_ARRAYSIZE ((domes_trace_ObjectKind)(domes_trace_ObjectKind_OBJECT_KIND_TIMEOUT+1))

#define domes_trace_Event_event_type_ENUMTYPE domes_trace_EventType
#define domes_trace_Event_category_ENUMTYPE domes_trace_Category


#define domes_trace_ObjectEntry_kind_ENUMTYPE domes_trace_ObjectKind





#define domes_trace_AckResponse_status_ENUMTYPE domes_trace_Status



/* Initializer values for message structs */
#define domes_trace_Event_init_default           {0, 0, _domes_trace_EventType_MIN, _domes_trace_Category_MIN, 0, 0}
#define domes_trace_TaskEntry_init_default       {0, "", 0, 0}
#define domes_trace_ObjectEntry_init_default     {0, _domes_trace_ObjectKind_MIN, ""}
#define domes_trace_TraceSessionInfo_init_default {0, 0, 0, 0, 0, 0, {domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default, domes_trace_TaskEntry_init_default}, 0, 0, 0, {domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default, domes_trace_ObjectEntry_init_default}, 0, "", {0, {0}}, {0, {0}}, {0, {0}}}
#define domes_trace_TraceDataChunk_init_default  {0, 0, {0, {0}}}
#define domes_trace_TraceDumpComplete_init_default {0, 0}
#define domes_trace_TraceStatusResponse_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define domes_trace_AckResponse_init_default     {_domes_trace_Status_MIN}
#define domes_trace_StreamBatch_init_default     {0, 0, {0, {0}}}
#define domes_trace_Event_init_zero              {0, 0, _domes_trace_EventType_MIN, _domes_trace_Category_MIN, 0, 0}
#define domes_trace_TaskEntry_init_zero          {0, "", 0, 0}
#define domes_trace_ObjectEntry_init_zero        {0, _domes_trace_ObjectKind_MIN, ""}
#define domes_trace_TraceSessionInfo_init_zero   {0, 0, 0, 0, 0, 0, {domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero, domes_trace_TaskEntry_init_zero}, 0, 0, 0, {domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero, domes_trace_ObjectEntry_init_zero}, 0, "", {0, {0}}, {0, {0}}, {0, {0}}}
#define domes_trace_TraceDataChunk_init_zero     {0, 0, {0, {0}}}
#define domes_trace_TraceDumpComplete_init_zero  {0, 0}
#define domes_trace_TraceStatusResponse_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define domes_trace_AckResponse_init_zero        {_domes_trace_Status_MIN}
#define domes_trace_StreamBatch_init_zero        {0, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define domes_trace_Event_timestamp_tag          1
#define domes_trace_Event_task_id_tag            2
#define domes_trace_Event_event_type_tag         3
#define domes_trace_Event_category_tag           4
#define domes_trace_Event_arg1_tag               5
#define domes_trace_Event_arg2_tag               6
#define domes_trace_TaskEntry_task_id_tag        1
#define domes_trace_TaskEntry_name_tag           2
#define domes_trace_TaskEntry_priority_tag       3
#define domes_trace_TaskEntry_core_affinity_mask_tag 4
#define domes_trace_ObjectEntry_object_id_tag    1
#define domes_trace_ObjectEntry_kind_tag         2
#define domes_trace_ObjectEntry_name_tag         3
#define domes_trace_TraceSessionInfo_pod_id_tag  1
#define domes_trace_TraceSessionInfo_event_count_tag 2
#define domes_trace_TraceSessionInfo_dropped_count_tag 3
#define domes_trace_TraceSessionInfo_start_timestamp_us_tag 4
#define domes_trace_TraceSessionInfo_end_timestamp_us_tag 5
#define domes_trace_TraceSessionInfo_tasks_tag   6
#define domes_trace_TraceSessionInfo_buffer_size_bytes_tag 7
#define domes_trace_TraceSessionInfo_trace_event_format_version_tag 9
#define domes_trace_TraceSessionInfo_objects_tag 10
#define domes_trace_TraceSessionInfo_discontinuity_count_tag 11
#define domes_trace_TraceSessionInfo_firmware_version_tag 12
#define domes_trace_TraceSessionInfo_app_elf_sha256_tag 13
#define domes_trace_TraceSessionInfo_app_image_sha256_tag 14
#define domes_trace_TraceSessionInfo_device_uid_tag 15
#define domes_trace_TraceDataChunk_offset_tag    1
#define domes_trace_TraceDataChunk_count_tag     2
#define domes_trace_TraceDataChunk_events_tag    3
#define domes_trace_TraceDumpComplete_total_events_tag 1
#define domes_trace_TraceDumpComplete_checksum_tag 2
#define domes_trace_TraceStatusResponse_initialized_tag 1
#define domes_trace_TraceStatusResponse_enabled_tag 2
#define domes_trace_TraceStatusResponse_streaming_tag 3
#define domes_trace_TraceStatusResponse_event_count_tag 4
#define domes_trace_TraceStatusResponse_dropped_count_tag 5
#define domes_trace_TraceStatusResponse_buffer_size_tag 6
#define domes_trace_TraceStatusResponse_stream_category_mask_tag 7
#define domes_trace_TraceStatusResponse_discontinuity_count_tag 8
#define domes_trace_AckResponse_status_tag       1
#define domes_trace_StreamBatch_sequence_tag     1
#define domes_trace_StreamBatch_dropped_tag      2
#define domes_trace_StreamBatch_events_tag       3

/* Struct field encoding specification for nanopb */
#define domes_trace_Event_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   task_id,           2) \
X(a, STATIC,   SINGULAR, UENUM,    event_type,        3) \
X(a, STATIC,   SINGULAR, UENUM,    category,          4) \
X(a, STATIC,   SINGULAR, UINT32,   arg1,              5) \
X(a, STATIC,   SINGULAR, UINT32,   arg2,              6)
#define domes_trace_Event_CALLBACK NULL
#define domes_trace_Event_DEFAULT NULL

#define domes_trace_TaskEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   task_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UINT32,   priority,          3) \
X(a, STATIC,   SINGULAR, UINT32,   core_affinity_mask,   4)
#define domes_trace_TaskEntry_CALLBACK NULL
#define domes_trace_TaskEntry_DEFAULT NULL

#define domes_trace_ObjectEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   object_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3)
#define domes_trace_ObjectEntry_CALLBACK NULL
#define domes_trace_ObjectEntry_DEFAULT NULL

#define domes_trace_TraceSessionInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pod_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   event_count,       2) \
X(a, STATIC,   SINGULAR, UINT32,   dropped_count,     3) \
X(a, STATIC,   SINGULAR, UINT32,   start_timestamp_us,   4) \
X(a, STATIC,   SINGULAR, UINT32,   end_timestamp_us,   5) \
X(a, STATIC,   REPEATED, MESSAGE,  tasks,             6) \
X(a, STATIC,   SINGULAR, UINT32,   buffer_size_bytes,   7) \
X(a, STATIC,   SINGULAR, UINT32,   trace_event_format_version,   9) \
X(a, STATIC,   REPEATED, MESSAGE,  objects,          10) \
X(a, STATIC,   SINGULAR, UINT32,   discontinuity_count,  11) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,  12) \
X(a, STATIC,   SINGULAR, BYTES,    app_elf_sha256,   13) \
X(a, STATIC,   SINGULAR, BYTES,    app_image_sha256,  14) \
X(a, STATIC,   SINGULAR, BYTES,    device_uid,       15)
#define domes_trace_TraceSessionInfo_CALLBACK NULL
#define domes_trace_TraceSessionInfo_DEFAULT NULL
#define domes_trace_TraceSessionInfo_tasks_MSGTYPE domes_trace_TaskEntry
#define domes_trace_TraceSessionInfo_objects_MSGTYPE domes_trace_ObjectEntry

#define domes_trace_TraceDataChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   count,             2) \
X(a, STATIC,   SINGULAR, BYTES,    events,            3)
#define domes_trace_TraceDataChunk_CALLBACK NULL
#define domes_trace_TraceDataChunk_DEFAULT NULL

#define domes_trace_TraceDumpComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_events,      1) \
X(a, STATIC,   SINGULAR, UINT32,   checksum,          2)
#define domes_trace_TraceDumpComplete_CALLBACK NULL
#define domes_trace_TraceDumpComplete_DEFAULT NULL

#define domes_trace_TraceStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     initialized,       1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2) \
X(a, STATIC,   SINGULAR, BOOL,     streaming,         3) \
X(a, STATIC,   SINGULAR, UINT32,   event_count,       4) \
X(a, STATIC,   SINGULAR, UINT32,   dropped_count,     5) \
X(a, STATIC,   SINGULAR, UINT32,   buffer_size,       6) \
X(a, STATIC,   SINGULAR, UINT32,   stream_category_mask,   7) \
X(a, STATIC,   SINGULAR, UINT32,   discontinuity_count,   8)
#define domes_trace_TraceStatusResponse_CALLBACK NULL
#define domes_trace_TraceStatusResponse_DEFAULT NULL

#define domes_trace_AckResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define domes_trace_AckResponse_CALLBACK NULL
#define domes_trace_AckResponse_DEFAULT NULL

#define domes_trace_StreamBatch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   SINGULAR, UINT32,   dropped,           2) \
X(a, STATIC,   SINGULAR, BYTES,    events,            3)
#define domes_trace_StreamBatch_CALLBACK NULL
#define domes_trace_StreamBatch_DEFAULT NULL

extern const pb_msgdesc_t domes_trace_Event_msg;
extern const pb_msgdesc_t domes_trace_TaskEntry_msg;
extern const pb_msgdesc_t domes_trace_ObjectEntry_msg;
extern const pb_msgdesc_t domes_trace_TraceSessionInfo_msg;
extern const pb_msgdesc_t domes_trace_TraceDataChunk_msg;
extern const pb_msgdesc_t domes_trace_TraceDumpComplete_msg;
extern const pb_msgdesc_t domes_trace_TraceStatusResponse_msg;
extern const pb_msgdesc_t domes_trace_AckResponse_msg;
extern const pb_msgdesc_t domes_trace_StreamBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define domes_trace_Event_fields &domes_trace_Event_msg
#define domes_trace_TaskEntry_fields &domes_trace_TaskEntry_msg
#define domes_trace_ObjectEntry_fields &domes_trace_ObjectEntry_msg
#define domes_trace_TraceSessionInfo_fields &domes_trace_TraceSessionInfo_msg
#define domes_trace_TraceDataChunk_fields &domes_trace_TraceDataChunk_msg
#define domes_trace_TraceDumpComplete_fields &domes_trace_TraceDumpComplete_msg
#define domes_trace_TraceStatusResponse_fields &domes_trace_TraceStatusResponse_msg
#define domes_trace_AckResponse_fields &domes_trace_AckResponse_msg
#define domes_trace_StreamBatch_fields &domes_trace_StreamBatch_msg

/* Maximum encoded size of messages (where known) */
#define DOMES_TRACE_TRACE_PB_H_MAX_SIZE          domes_trace_TraceSessionInfo_size
#define domes_trace_AckResponse_size             3
#define domes_trace_Event_size                   28
#define domes_trace_ObjectEntry_size             25
#define domes_trace_StreamBatch_size             271
#define domes_trace_TaskEntry_size               35
#define domes_trace_TraceDataChunk_size          271
#define domes_trace_TraceDumpComplete_size       12
#define domes_trace_TraceSessionInfo_size        1019
#define domes_trace_TraceStatusResponse_size     36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
