/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "trace.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domes_trace_Event, domes_trace_Event, AUTO)


PB_BIND(domes_trace_TaskEntry, domes_trace_TaskEntry, AUTO)


PB_BIND(domes_trace_Metadata, domes_trace_Metadata, 2)


PB_BIND(domes_trace_DataHeader, domes_trace_DataHeader, AUTO)


PB_BIND(domes_trace_DumpEnd, domes_trace_DumpEnd, AUTO)


PB_BIND(domes_trace_StatusResponse, domes_trace_StatusResponse, AUTO)


PB_BIND(domes_trace_AckResponse, domes_trace_AckResponse, AUTO)











